import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "18%",
  },
  bs_2: {
    height: "100%",
    width: "52%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "18%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  // starts here
  scroll_section: {
    width: "100%",
    height: "100%",
    // backgroundColor: "red",
    marginTop: 20,
    zIndex: 100,
  },
  indi_character: {
    height: 120,
    width: "86%",
    alignSelf: "center",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
    marginBottom: 15,
  },
  ic_top: {
    height: "50%",
    width: "100%",
    // backgroundColor: "red",
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ic_bottom: {
    height: "50%",
    width: "100%",
    // backgroundColor: "green",
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    justifyContent: "center",
  },
  ic_ch_text_section: {
    height: "100%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  ic_ch_text: {
    // height: "100%",
    width: "fit-content",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    width: "100%",
  },
  ic_scrore_section: {
    height: 40,
    width: 120,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 100,
  },
  ic_score_text: {
    // height: "100%",
    // width: "100%",
    color: "white",
    letterSpacing: 0.7,
  },
  ic_b_numbers: {
    width: "100%",
    height: 30,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // backgroundColor: "red",
  },
  range_outer: {
    height: 5,
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 100,
    overflow: "hidden",
  },
  range_inner: {
    height: "100%",
    width: "20%",
    backgroundColor: "#FF25F0",
    borderRadius: 100,
  },
  ic_b_num_text: {
    height: "fit-content",
    width: "fit-content",
    color: "white",
    fontSize: 16,
  },
  empty_section: {
    height: 50,
    width: "100%",
  },
  loading_whole: {
    height: screenHeight - 300,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  nsts: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
