import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    flex: 1,
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_absolute: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: 20,
    zIndex: 100,
  },
  bs_1_circle_absolute_2: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: 70,
    zIndex: 100,
  },
  bs_1_circle_absolute_3: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: 120,
    zIndex: 100,
  },
  bs_1_circle_absolute_4: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: 170,
    zIndex: 100,
  },
  bs_1_circle_absolute_image: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 10,
    right: 40,
    zIndex: 100,
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  input_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
    marginTop: 20,
    zIndex: 10,
  },
  input_whole_section_audio: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    // alignItems: "center",
    marginBottom: 10,
    position: "relative",
    marginTop: 20,
    zIndex: 10,
    paddingLeft: 20,
    position: "relative",
    // backgroundColor: "red",
  },
  input_whole_section_down: {
    height: "90%",
    width: "80%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    zIndex: 10,
  },
  input_whole_section_down_circle: {
    height: 45,
    width: 45,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    zIndex: 10,
    borderRadius: 50,
  },
  input_section_nsvg: {
    height: "100%",
    width: "100%",
    paddingLeft: 20,
    flexDirection: "row",
    // backgroundColor: "green",
  },
  input_section_nsvg_svg: {
    heihgt: 50,
    width: 50,
    // paddingLeft: 20,
    flexDirection: "row",
    // backgroundColor: "green",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  input_section_svg: {
    height: "100%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "green",
  },
  input: {
    height: "100%",
    width: "100%",
    letterSpacing: 1,
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    // paddingBottom: 0,
    // backgroundColor: "red",
    overflow: "hidden",
  },
  input2: {
    height: "100%",
    width: "100%",
    letterSpacing: 1,
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    // paddingBottom: 0,
    overflow: "hidden",
  },
  input_inner_section1: {
    height: "100%",
    width: "90%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  input_inner_section1_audio: {
    height: 60,
    width: 60,
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // overflow: "hidden",
    // justifyContent: "space-between",
    // gap: 12,
  },
  input_inner_section: {
    height: "100%",
    width: "100%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  journal_content: {
    width: "90%",
    // backgroundColor: "red",
    alignSelf: "center",
    minHeight: "fit-content",
    verticalAlign: "top",
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
  tag_section: {
    height: 120,
    width: "100%",
    zIndex: 100,
  },
  all_tags_section: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    paddingLeft: 10,
    // alignItems: "center",
  },
  all_tags_section_in_journal: {
    height: 60,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    paddingLeft: 10,
    // alignItems: "center",
  },
  all_tag_section_outside: {
    height: "45%",
    width: "100%",
  },
  indi_tag: {
    height: "80%",
    paddingLeft: 15,
    paddingRight: 15,
    display: "flex",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    zIndex: 100,
  },
  indi_tag_active: {
    height: "80%",
    paddingLeft: 15,
    paddingRight: 15,
    display: "flex",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    zIndex: 100,
    backgroundColor: "white",
  },
  indi_tag_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  indi_tag_text_active: {
    fontSize: 14,
    color: "rgba(30, 63, 142, 1)",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  tag_space: {
    height: "100%",
    width: 100,
  },
  input_section: {
    height: "45%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 5,
    alignItems: "center",
    // backgroundColor: "red",
  },
  input_section1: {
    height: "45%",
    width: "85%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 5,
    alignItems: "center",
    // backgroundColor: "red",
  },
  stroke_is: {
    height: "90%",
    width: "80%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  mic_is: {
    height: 50,
    width: 50,
    borderRadius: 500,
  },
  stroke_is_in: {
    height: "98%",
    width: "99%",
    borderRadius: 50,
  },
  cp_section: {
    height: "100%",
    width: "28%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  time_line_whole: {
    height: "100%",
    width: "80%",
    display: "flex",
    justifyContent: "center",
    // alignItems: "center",
  },
  time_line_outer: {
    height: 4,
    width: "92%",
    borderRadius: 50,
    backgroundColor: "#ffffff80",
  },
  time_line_done: {
    height: "100%",
    width: "50%",
  },
  journal_img: {
    height: 300,
    width: "90%",
    borderRadius: 5,
    objectFit: "cover",
  },
  img_section: {
    width: "100%",
    paddingLeft: 20,
    marginBottom: 20,
    position: "relative",
  },
  sv_empty_space: {
    height: 50,
    width: "100%",
  },
  cut_circle: {
    height: 20,
    width: 20,
    borderRadius: 20,
    position: "absolute",
    top: -5,
    left: 60,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  whole_camera_section: {
    height: "100%",
    width: "100%",
    backgroundColor: "black",
  },
  camera: {
    height: "80%",
    width: "100%",
  },
  camera_options: {
    height: "20%",
    width: "100%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
  },
  co_small: {
    height: 40,
    width: 40,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  co_large: {
    height: 70,
    width: 70,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: "white",
  },
  cue_section: {
    width: "100%",
  },
  journal_cue: {
    width: "92%",
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    padding: 15,
  },
  indi_cue_text: {
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
