import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const screenWidth = Dimensions.get("window").width;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    marginTop: 5,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_2_: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  user_msg: {
    width: "100%",
    paddingLeft: 20,
    display: "flex",
    marginBottom: 20,
  },
  me_msg: {
    width: "100%",
    paddingRight: 20,
    display: "flex",
    alignItems: "flex-end",
    marginBottom: 20,
  },
  a_user_msg: {
    padding: 15,
    width: "90%",
    backgroundColor: "#5264A5",
    borderRadius: 10,
    borderBottomLeftRadius: 0,
  },
  a_me_msg: {
    padding: 15,
    width: "90%",
    backgroundColor: "#009DFF",
    borderRadius: 10,
    borderBottomRightRadius: 0,
  },
  me_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
    marginBottom: 5,
  },
  user_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  time: {
    fontSize: 14,
    color: "#ffffff60",
    marginTop: 10,
  },
  input_Section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    zIndex: 10,
    marginTop: 10,
  },
  input_inner: {
    height: "100%",
    width: "90%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    position: "relative",
  },
  input: {
    height: "100%",
    width: "83%",
    paddingLeft: 20,
    color: "white",
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    // backgroundColor: "red",
  },
  btn: {
    height: 50,
    width: 50,
    borderRadius: 50,
    backgroundColor: "#ffffff10",
    position: "absolute",
    right: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btn_full_1: {
    height: 40,
    width: 40,
    borderRadius: 50,
    backgroundColor: "#ffffff10",
    // position: "absolute",
    // right: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btn_full_2: {
    height: 40,
    width: 40,
    borderRadius: 50,
    backgroundColor: "#ffffff10",
    // position: "absolute",
    // right: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btn_full: {
    height: 50,
    width: 110,
    borderRadius: 50,
    backgroundColor: "#ffffff10",
    position: "absolute",
    right: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 15,
  },
  btn2: {
    height: 50,
    width: 50,
    borderRadius: 50,
    // backgroundColor: "red",
    position: "absolute",
    right: 80,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btn3: {
    height: 50,
    width: 50,
    borderRadius: 50,
    // backgroundColor: "red",
    position: "absolute",
    right: 120,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btn4: {
    height: 50,
    width: 50,
    borderRadius: 50,
    // backgroundColor: "red",
    position: "absolute",
    right: 160,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  input_whole_section_btn: {
    height: 50,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
  },
  input_whole_section_btn_ia: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
    zIndex: 10,
  },
  input_whole_section_btn_ac: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 5,
    zIndex: 10,
  },
  input_inner_section_btn_ac: {
    height: "100%",
    width: "95%",
    borderRadius: 500,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  input_inner_section_btn: {
    height: "100%",
    width: "80%",
    borderRadius: 500,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  input_inner_section_btn_ia: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    // color: "#009DFF",
    color: "rgba(30, 63, 142, 1)",
    fontFamily: "Poppins-Regular",
    textTransform: "capitalize",
  },
  login_text_ia: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  bs_whole_view: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    gap: 10,
  },
  calendar: {
    width: screenWidth - 20,
    borderRadius: 6,
    height: 340,
  },
  main_content_section: {
    height: "fit-content",
    width: "100%",
    paddingLeft: 20,
    paddingRight: 30,
    marginTop: 5,
  },
  title_section: {
    height: "fit-content",
    width: "100%",
    marginTop: 10,
    marginBottom: 10,
  },
  title: {
    fontSize: 18,
    fontFamily: "Poppins-Medium",
    color: "white",
    letterSpacing: 0.7,
  },
  list_title: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    color: "white",
    letterSpacing: 0.7,
  },
  des_section: {
    height: "fit-content",
    width: "100%",
    marginBottom: 10,
  },
  des: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffffb9",
    letterSpacing: 0.7,
  },
  list_title_section: {
    height: "fit-content",
    width: "100%",
  },
  des: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffffb9",
    letterSpacing: 0.7,
  },
  list_item_indi: {
    height: "fit-content",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    gap: 6,
    marginBottom: 5,
  },
  lii_dot_section: {
    height: "100%",
    width: "4%",
    alignItems: "center",
    paddingTop: 7,
  },
  dot: {
    height: 6,
    width: 6,
    backgroundColor: "#ffffffb9",
    borderRadius: 50,
  },
  list_item_text: {
    fontSize: 14,
    color: "#ffffffb9",
  },
  ida_to: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  ida_text: {
    fontSize: 14,
    color: "#ffffffb9",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  sa_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
    marginTop: 5,
  },
  dt_whole_section: {
    height: "fit-content",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 10,
    marginTop: 10,
  },
  date_time_section_d: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  date_time_section_d_active: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(30, 63, 142, 1)",
    position: "relative",
  },
  dt_text_100: {
    fontSize: 13,
    fontFamily: "Poppins-Regular",
    color: "white",
    textAlign: "flex-start",
    width: "100%",
    textAlign: "center",
  },
  pg_s_bottom: {
    height: "fit-content",
    width: "100%",
    padding: 20,
    paddingBottom: 5,
  },
  empty_s_view: {
    height: 200,
    width: "100%",
  },
  outer_booking: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  session_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Medium",
    marginBottom: 8,
  },
  session_text_: {
    fontSize: 15,
    color: "white",
    fontFamily: "Poppins-Regular",
    marginBottom: 8,
  },
  session_text_discount: {
    fontSize: 12,
    color: "white",
    // fontFamily: "Poppins-Regular",
    marginBottom: 8,
    // lineHeight: 15,
  },
  first_empty_section: {
    height: 10,
    width: "100%",
  },
  discount_section: {
    height: 20,
    width: 20,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#ffffff30",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  side_by_side: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  bs_whole_view: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    gap: 10,
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    paddingLeft: 25,
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  yourstory_input_section: {
    minHeight: 150,
    height: "fit-content",
    width: "90%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    zIndex: 10,
    padding: 10,
    marginTop: 10,
    position: "relative",
    paddingBottom: 10,
  },
  whole_camera_section: {
    height: screenHeight,
    width: "100%",
    backgroundColor: "black",
    position: "absolute",
  },
  camera: {
    height: "80%",
    width: "100%",
  },
  camera_options: {
    height: "20%",
    width: "100%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
  },
  co_small: {
    height: 40,
    width: 40,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  co_large: {
    height: 70,
    width: 70,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: "white",
  },
  cm_text: {
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
  chat_img: {
    height: 320,
    width: "100%",
    objectFit: "cover",
    borderRadius: 6,
  },
});
export default styles;
