import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "130%",
    width: "100%",
    position: "relative",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 55,
    width: 55,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "#ffffff90",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  indi_up: {
    height: 200,
    width: "90%",
    marginTop: 10,
    alignSelf: "center",
    borderRadius: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  indi_up_inner: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1.5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  upy_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
    marginTop: 10,
  },
  mpp_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffff80",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 45,
    // marginTop: 370,
    zIndex: 10,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  profile_img: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    objectFit: "cover",
  },
  empty_view: {
    height: 200,
    width: "100%",
  },
  cross_btn: {
    height: 40,
    width: 40,
    borderRadius: 100,
    backgroundColor: "white",
    position: "absolute",
    right: 5,
    top: 5,
    zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // elevation: 10,
  },
  camera_section: {
    height: 50,
    width: 50,
    position: "absolute",
    right: 30,
    top: screenHeight - 80,
    backgroundColor: "white",
    borderRadius: 100,
    zIndex: 1000,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  whole_camera_section: {
    height: screenHeight,
    width: "100%",
    backgroundColor: "black",
    position: "absolute",
  },
  camera: {
    height: "80%",
    width: "100%",
  },
  camera_options: {
    height: "20%",
    width: "100%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
  },
  co_small: {
    height: 40,
    width: 40,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  co_large: {
    height: 70,
    width: 70,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: "white",
  },
  camera_cross_section: {
    height: 30,
    width: 30,
    backgroundColor: "white",
    borderRadius: 100,
    position: "absolute",
    top: 60,
    right: 20,
    zIndex: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  welcome_view: {
    // height: "fit-content",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  welcome_text: {
    fontSize: 24,
    color: "white",
    fontWeight: "400",
    letterSpacing: 0.7,
    fontFamily: "Poppins-ThinItalic",
    textAlign: "center",
    width: "100%",
  },
  welcome_des: {
    width: "100%",
    fontSize: 18,
    color: "#ffffffa1",
    fontSize: 16,
    fontWeight: "300",
    marginTop: 5,
    textAlign: "center",
  },
});
export default styles;
