import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
import { Dimensions } from "react-native";
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  welcome_view: {
    // height: "fit-content",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  welcome_text: {
    fontSize: 30,
    color: "white",
    fontWeight: "400",
    // letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    textAlign: "center",
    width: "100%",
  },
  welcome_des: {
    width: "100%",
    fontSize: 18,
    color: "#ffffffa1",
    fontSize: 16,
    fontWeight: "300",
    marginTop: 5,
    textAlign: "center",
  },
  input_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    zIndex: 100,
    marginTop: (screenHeight * 16) / 100,
  },

  input_inner_section: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  svg_circle: {
    height: 60,
    width: 40,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  svg_circle_eye: {
    height: 60,
    width: 60,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },

  input_section: {
    height: "100%",
    width: 220,
  },
  input_section_text: {
    height: "100%",
    width: 180,
    display: "flex",
    justifyContent: "center",
  },
  input: {
    height: "100%",
    width: "100%",
    letterSpacing: 1,
    fontSize: 16,
    color: "white",
    // backgroundColor: "red",
  },
  input_text: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff90",
    paddingLeft: 6,
    textTransform: "capitalize",
  },
  input_text_active: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff",
    paddingLeft: 6,
    // textTransform: "capitalize",
  },
  fp_whole: {
    width: "82%",
    // height: "fit-content",
    display: "flex",
    alignItems: "center",
    marginBottom: 25,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "center",
  },
  fp_inner: {
    width: "85%",
    // height: "fit-content",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "red",
    alignItems: "center",
  },
  fp_text: {
    textAlign: "left",
    color: "#ffffff90",
    letterSpacing: 1,
    width: "90%",
  },
  fp_inner_text: {
    color: "#ffffff",
    letterSpacing: 1,
    textDecorationColor: "#ffffff",
    textDecorationLine: "underline",
  },
  fp_text_center: {
    width: "100%",
    // textAlign: "center",
    color: "#ffffff90",
    letterSpacing: 1,
    // textDecorationColor: "#ffffff90",
    // textDecorationLine: "underline",
    lineHeight: 18,
    fontSize: 12,
  },
  login_text: {
    fontSize: 18,
    // fontWeight: "700",
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  su_text: {
    color: "white",
    textDecorationLine: "underline",
  },
  role_section: {
    position: "absolute",
    zIndex: 10,
    bottom: 0,
  },
  bs_whole_view: {
    height: "100%",
    alignItems: "center",
    gap: 10,
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_3: {
    height: "100%",
    width: "23%",
  },
  bs_1_circle: {
    height: 55,
    width: 55,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  fp_whole_text: {
    width: "85%",
    // height: "fit-content",
    // backgroundColor: "green",
  },
  fp_whole_svg_section: {
    width: "10%",
    // height: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    // backgroundColor: "red",
  },
  profile_pic_section: {
    height: 200,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 15,
  },
  profile_img_section: {
    height: 120,
    width: 120,
    borderRadius: 200,
    position: "relative",
  },
  profile_img: {
    height: "100%",
    width: "100%",
    borderRadius: 200,
  },
  camera_icon: {
    height: 40,
    width: 40,
    borderRadius: 50,
    zIndex: 100,
    position: "absolute",
    top: 1,
    right: 1,
    backgroundColor: "#1E357E",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.38)",
  },
  camera_icon_svg: {
    height: 20,
    width: 20,
  },
  label: {
    height: "100%",
    width: "70%",
    display: "flex",
    justifyContent: "center",
    // backgroundColor: "red",
  },
  label_text: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff80",
    paddingLeft: 4,
  },
  label_text_active: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff",
    paddingLeft: 4,
  },
  app_text: {
    fontSize: 18,
    color: "#fff",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
