import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: screenHeight - 55 - 10 - 10,
    width: "100%",
    zIndex: 10,
    display: "flex",
    paddingTop: 120,

    // backgroundColor: "red",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  //   starts here
  welcome_text: {
    fontSize: 26,
    width: "100%",
    color: "white",
    textAlign: "center",
    fontFamily: "Poppins-Regular",
    // marginTop: 50,
  },
  pda_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#ffffff",
    textAlign: "center",
    marginBottom: 50,
  },
  input_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 30,
  },

  input_inner_section: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  svg_circle: {
    height: 60,
    width: 40,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  svg_circle_eye: {
    height: 60,
    width: 60,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },

  input_section: {
    height: "100%",
    width: 210,
    // backgroundColor: "green",
  },
  input_section_text: {
    height: "100%",
    width: 180,
    display: "flex",
    justifyContent: "center",
  },
  input: {
    height: "100%",
    width: "100%",
    letterSpacing: 1,
    fontSize: 14,
    color: "white",
    // fontFamily: "Poppins-Regular",
    // paddingBottom: 0,
    // backgroundColor: "red",
    overflow: "hidden",
  },
  input_text: {
    letterSpacing: 1,
    fontSize: 14,
    color: "#ffffff90",
    paddingLeft: 6,
    textTransform: "capitalize",
    // fontFamily: "Poppins-Regular",
  },
  input_text_active: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff",
    paddingLeft: 6,
    textTransform: "capitalize",
  },
  fp_text_section: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  su_text_section: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  fp_text: {
    color: "rgba(255, 255, 255, 0.5)",
    textDecorationColor: "rgba(255, 255, 255, 0.5)",
    textDecorationLine: "underline",
    textAlign: "right",
    width: "80%",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  su_text: {
    color: "rgba(255, 255, 255, 0.5)",
    textDecorationColor: "rgba(255, 255, 255, 0.5)",
    // textDecorationLine: "underline",
    textAlign: "center",
    width: "100%",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  su: {
    color: "white",
    textDecorationLine: "underline",
  },
  svg_view: {
    height: "fit-content",
    width: "fit-content",
    borderRadius: 100,
    overflow: "hidden",
  },
  cc_view: {
    height: "100%",
    widthL: "fit-content",
    display: "flex",
    justifyContent: "center",
  },
  cc_text: {
    fontSize: 16,
    color: "white",
    // fontWeight: 500,
  },
  drop_down_section: {
    height: "100%",
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
  },
  dd_svg: {
    height: 20,
    width: 20,
  },
  flag: {
    height: 20,
    width: 20,
    borderRadius: 100,
    objectFit: "cover",
  },
  svg_circle_: {
    height: 50,
    width: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 3.5,
    // marginBottom: 5,
    marginLeft: 5,
    // backgroundColor: "red",
  },
  bs_whole_view: {
    height: "100%",
    alignItems: "center",
    gap: 10,
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text_section_flag: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    marginRight: 10,
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
  },
  last_empty_space_rb: {
    height: 30,
    width: "100%",
  },
  country_scroll: {
    width: "100%",
    height: "100%",
  },
});
export default styles;
