import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "85%",
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion: {
    height: 200,
    width: "100%",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue_: {
    textAlign: "center",
    fontSize: 18,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    position: "fixed",
    // backgroundColor: "red",
    top: 0,
  },
  subs_section: {
    height: 510,
    width: 300,
    borderRadius: 20,
    overflow: "hidden",
    zIndex: 10,
  },
  subs_inner: {
    height: "100%",
    width: "100%",
    borderWidth: 1,
    borderRadius: 20,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    alignItems: "center",
  },
  cue_text: {
    fontSize: 36,
    color: "white",
    fontFamily: "Poppins-Regular",
    marginTop: 30,
    letterSpacing: 0.7,
    lineHeight: 36,
    width: "100%",
    textAlign: "center",
  },
  pda_text: {
    fontSize: 16,
    color: "#ffffff80",
    fontFamily: "Poppins-Light",
    width: "100%",
    textAlign: "center",
  },
  qg_text: {
    fontSize: 15,
    fontFamily: "Poppins-Regular",
    color: "white",
    textAlign: "center",
    marginTop: 30,
    width: "80%",
    width: "100%",
    textAlign: "center",
  },
  ac_text: {
    fontSize: 12,
    fontFamily: "Poppins-Light",
    color: "#ffffff80",
    textAlign: "center",
    width: "90%",
    width: "100%",
    textAlign: "center",
    marginTop: 6,
    width: "90%",
    alignSelf: "center",
  },
  aed_text: {
    fontSize: 24,
    color: "white",
    fontFamily: "Poppins-Regular",
    marginTop: 45,
    lineHeight: 28,
    width: "100%",
    textAlign: "center",
  },
  a_text: {
    fontSize: 18,
    color: "#ffffff80",
    width: "100%",
    textAlign: "center",
    fontFamily: "Poppins-Light",
    lineHeight: 28,
  },
  io_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
    width: "100%",
    textAlign: "center",
    marginTop: 3,
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 60,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 20,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  day_3_trial: {
    fontSize: 14,
    color: "#ffffff80",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
