import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    marginTop: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "70%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "10%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  bia_section: {
    height: 45,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "red",
    justifyContent: "space-evenly",
    marginTop: 20,
  },
  bia_section_indi: {
    height: "100%",
    width: "fit-content",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 15,
    paddingRight: 15,
  },
  bia_text: {
    color: "white",
    fontFamily: "Poppins-Regular",
    fontSize: 14,
  },
  yourstory_input_section: {
    // height: 400,
    width: "92%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    zIndex: 10,
    padding: 10,
    marginTop: 20,
    alignSelf: "center",
  },
  input_section: {
    height: "100%",
    width: "100%",
    textAlignVertical: "top",
    fontFamily: "Poppins-Regular",
    fontSize: 14,
    color: "white",
  },
  ts_text: {
    fontSize: 20,
    fontFamily: "Poppins-Medium",
    color: "white",
    textAlign: "center",
    marginTop: 10,
  },
  pg_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    marginTop: 20,
    color: "white",
    paddingLeft: 10,
  },
  pg_section: {
    height: 250,
    width: "100%",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginTop: 5,
    padding: 5,
  },
  line: {
    height: 2,
    width: "90%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    alignSelf: "center",
  },
  pg_s_top: {
    height: "60%",
    width: "100%",
  },
  pg_s_bottom: {
    height: "40%",
    width: "100%",
    padding: 5,
  },
  sa_text: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    color: "white",
    marginTop: 5,
  },
  date_time_section_d: {
    height: 40,
    width: "42%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  date_time_section_t: {
    height: 40,
    width: "55%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  dt_text: {
    fontSize: 12,
    // fontFamily: "Poppins-Regular",
    color: "white",
  },
  dt_whole_section: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  btp_section: {
    height: 40,
    width: "100%",
    padding: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  discount_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    padding: 10,
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
  },
  btp_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  oval: {
    height: 40,
    width: "fit-content",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    paddingLeft: 12,
    paddingRight: 12,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oval_large: {
    height: 40,
    width: "fit-content",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    paddingLeft: 22,
    paddingRight: 22,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oval_text: {
    fontSize: 14,
    color: "white",
    // fontFamily: "Poppins-Regular",
  },
  amount_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
