import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  img_section: {
    marginTop: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  img: {
    height: 100,
    width: 100,
    borderRadius: 10,
    objectFit: "cover",
  },
  c_name: {
    fontSize: 20,
    fontFamily: "Poppins-Medium",
    marginTop: 10,
    color: "white",
  },
  indi_banner_section: {
    height: 170,
    width: "90%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 20,
  },
  indi_banner_section_fc: {
    height: 210,
    width: "90%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 20,
  },
  inner_ibs: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    padding: 15,
  },
  title_section: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  tim_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  pricing_section: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  strike_price: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    textDecorationLine: "line-through",
    textDecorationColor: "rgba(255, 255, 255, 0.6)",
    color: "rgba(255, 255, 255, 0.6)",
  },
  a_price: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  vbp_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  indi_vbp: {
    height: "100%",
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    paddingLeft: 12,
    paddingRight: 12,
    gap: 6,
  },
  vbp_text: {
    color: "white",
    fontFamily: "Poppins-Regular",
    fontSize: 12,
  },
  dt_whole_section: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  btp_section: {
    height: 40,
    width: "100%",
    padding: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  discount_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    padding: 10,
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
  },
  btp_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  date_time_section_d: {
    height: 40,
    width: "42%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  date_time_section_t: {
    height: 40,
    width: "55%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  dt_text: {
    fontSize: 12,
    // fontFamily: "Poppins-Regular",
    color: "white",
  },
  btn: {
    height: 40,
    width: "100%",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1.5,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    marginTop: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  add_text: {
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Medium",
  },
});
export default styles;
