import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 14,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  indi_banner_section: {
    height: 60,
    width: "90%",
    borderRadius: 50,
    alignSelf: "center",
    marginTop: 10,
  },
  inner_ibs: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
  },
  iibs_text_input: {
    fontSize: 14,
    color: "#ffffff",
    height: "100%",
    width: "100%",
    fontFamily: "Poppins-Regular",
  },
  inner_ibs_sb: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
    paddingRight: 20,
    justifyContent: "space-between",
  },
  iibs_text: {
    fontSize: 16,
    color: "#ffffff",
    fontFamily: "Poppins-Regular",
  },
  indi_banner_section_large2: {
    height: 200,
    width: "90%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 10,
  },
  inner_ibs_large: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    // padding: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  acs_text: {
    fontSize: 18,
    fontFamily: "Poppins-Regular",
    color: "white",
    marginBottom: 40,
  },
  from_to_section: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  from_to_text_f: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
    width: "50%",
    textAlign: "center",
  },
  from_to_text_t: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
    width: "50%",
    textAlign: "center",
  },
  distribution_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    gap: 20,
    marginTop: 6,
  },
  indi_dis_section: {
    height: "100%",
    width: "fit-content",
    minWidth: 150,
    paddingLeft: 15,
    paddingRight: 15,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  percent: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  note: {
    width: "90%",
    marginTop: 20,
    alignSelf: "center",
    textAlign: "center",
    color: "#ffffff80",
    fontFamily: "Poppins-Regular",
  },
  upp_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
    marginTop: 20,
  },
  bs_whole_view: {
    height: "100%",
    alignItems: "center",
    gap: 10,
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  img: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
    borderRadius: 20,
  },
  yourstory_input_section: {
    // height: 400,
    width: "90%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    zIndex: 10,
    padding: 8,
    // marginTop: 20,
    alignSelf: "center",
    paddingBottom: 10,
    marginBottom: 10,
    marginTop: 10,
  },
  discription_input: {
    width: "100%",
    height: 300,
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    padding: 10,
  },
});
export default styles;
