import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  search_section_whole: {
    height: 50,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 30,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  search_section: {
    width: "70%",
    height: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 50,
  },
  filter_section: {
    height: 50,
    width: 50,
    borderRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  finter_section_in: {
    height: "97%",
    width: "96%",
    borderRadius: 20,
    backgroundColor: "rgba(51, 80, 148, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  search_section_input: {
    height: "100%",
    width: "100%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
  },
  search_svg_section: {
    height: "100%",
    width: "20%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  serach_input_section: {
    height: "100%",
    width: "80%",
  },
  sis_input: {
    height: "100%",
    width: "100%",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  options: {
    // height: 60,
    width: "100%",
    // backgroundColor: "red",
  },
  outer_h_sv: {
    height: 45,
    width: "100%",
    marginTop: 10,
  },
  indi_options: {
    paddingLeft: 20,
    paddingRight: 20,
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 100,
    marginRight: 10,
  },
  indi_option_text: {
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  left_ep: {
    height: "100%",
    width: 25,
  },
  main_sv: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    // backgroundColor: "red",
    justifyContent: "center",
    gap: 20,
    marginTop: 10,
  },
  indi_product: {
    height: 205,
    width: 150,
    // backgroundColor: "green",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  indi_p_img_section: {
    height: 90,
    width: "94%",
    // backgroundColor: "red",
    alignSelf: "center",
    borderRadius: 15,
    marginTop: 4,
    overflow: "hidden",
  },
  product_image: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
  },
  rate_p_section: {
    display: "flex",
    flexDirection: "row",
    marginTop: 8,
    paddingLeft: 8,
    gap: 10,
    alignItems: "center",
  },
  price_buy_section: {
    height: "20%",
    width: "100%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    marginTop: 8,
    paddingLeft: 4,
    paddingRight: 4,
  },
  product_name: {
    fontSize: 14,
    fontWeight: "400",
    letterSpacing: 0.7,
    paddingLeft: 6,
    paddingRight: 4,
    marginTop: 4,
    color: "white",
  },
  rate_text: {
    fontSize: 14,
    color: "white",
  },
  buy_now_btn: {
    height: 30,
    width: "55%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  buy_now_text: {
    fontSize: 12,
    color: "white",
  },
  price_cut: {
    color: "rgba(255, 255, 255, 0.5)",
    fontSize: 8,
    textAlign: "right",
    textDecorationLine: "line-through",
  },
  price: {
    color: "rgba(255, 255, 255, 1)",
    fontSize: 12,
    textAlign: "right",
  },
  price_section_whole: {
    width: "45%",
    height: "100%",
    paddingRight: 6,
  },
  all_pro_section: {
    height: 50,
    width: "100%",
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // backgroundColor: "red",
    marginTop: 20,
    zIndex: 10,
  },
  al_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  ap_section: {
    paddingLeft: 18,
    paddingRight: 18,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    height: "80%",
    display: "flex",
    justifyContent: "center",
    borderRadius: 50,
  },
  ap_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  sv_main: {
    height: 620,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 20,
    zIndex: 10,
  },
  indi_profile: {
    height: "100%",
    width: 325,
    // backgroundColor: "green",
    borderRadius: 20,
    overflow: "hidden",
    marginRight: 20,
  },
  start_view: {
    height: "100%",
    width: 30,
  },
  profile_img_Section: {
    height: "40%",
    width: "100%",
    backgroundColor: "red",
    position: "relative",
    overflow: "hidden",
  },
  profile_img: {
    height: "100%",
    width: 325,
    objectFit: "cover",
  },
  bottom_section: {
    height: "60%",
    width: "100%",
  },
  name_rate_section: {
    height: 40,
    width: "100%",
    justifyContent: "center",
    fontFamily: "Poppins-Regular",
    alignItems: "center",
  },
  egl_section: {
    height: 25,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
  },
  egl_section_story: {
    height: "fit-content",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "green",
    alignItems: "center",
    // paddingLeft: 12,
    paddingTop: 5,
    // paddingRight: 12,
  },
  egl_section_: {
    height: 25,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
  },
  egl_section_af: {
    height: 130,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
  },
  about_Section: {
    width: "100%",
    // backgroundColor: "blue",
    paddingLeft: 15,
    paddingRight: 15,
    marginTop: 15,
  },
  btn_section_: {
    height: 50,
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginTop: 20,
  },
  about_text: {
    fontSize: 13,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "300",
    fontFamily: "Poppins-Regular",
  },
  btn: {
    height: "75%",
    width: "45%",
    backgroundColor: "rgba(181, 195, 227, 0.1)",
    borderRadius: 60,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  name_rate: {
    height: "100%",
    width: "100%",
    // backgroundColor: "green",
    display: "flex",
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: "center",
  },
  name: {
    height: "100%",
    width: "fit-content",
    fontSize: 21,
    color: "white",
    // backgroundColor: "red",
    verticalAlign: "bottom",
    fontFamily: "Poppins-Medium",
    marginTop: 30,
  },
  empty_space_for_key: {
    height: 10,
  },
  indi_egl: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    paddingLeft: 10,
    paddingRight: 10,
    width: "fit-content",
  },
  indi_egl_story: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    paddingLeft: 10,
    paddingRight: 10,
    width: "fit-content",
  },
  egl_value: {
    fontSize: 15,
    color: "white",
    letterSpacing: 0.7,
    width: "fit-content",
    fontFamily: "Poppins-Regular",
  },
  egl_value_key: {
    fontSize: 17,
    color: "white",
    letterSpacing: 0.7,
    width: "fit-content",
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
  },
  price_time_section_story: {
    height: "fit-content",
    // marginTop: 10,
    width: "94%",
    alignSelf: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 6,
    padding: 10,
  },
  description: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  last_es: {
    height: 100,
    width: "100%",
  },
  save_coach_btn: {
    height: 40,
    width: 40,
    borderRadius: 50,
    backgroundColor: "rgba(46, 45, 45, 0.15)",
    position: "absolute",
    top: 10,
    right: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.48)",
    backdropFilter: "blur(10px)",
  },
});
export default styles;
