import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const screenWidth = Dimensions.get("window").width;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    // marginTop: 5,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "70%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    // backgroundColor: "red",
  },
  bia_section: {
    height: 45,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "red",
    justifyContent: "space-evenly",
    marginTop: 20,
    zIndex: 10,
  },
  bia_section_sv: {
    height: 45,
    width: "100%",
    display: "flex",
    // flexDirection: "row",
    // backgroundColor: "red",
    // justifyContent: "space-evenly",
    marginTop: 20,
    zIndex: 10,
    gap: 20,
  },
  sv_ev: {
    height: "100%",
    width: 20,
  },
  bia_section_indi: {
    height: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 15,
    paddingRight: 15,
  },
  bia_section_indi_active: {
    height: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 15,
    paddingRight: 15,
    backgroundColor: "rgba(255, 255, 255, 0.09)",
  },
  bia_text: {
    color: "white",
    fontFamily: "Poppins-Regular",
    fontSize: 14,
  },
  yourstory_input_section: {
    // height: 400,
    width: "95%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    zIndex: 10,
    padding: 8,
    marginTop: 20,
    alignSelf: "center",
  },
  yourstory_input_section_inner: {
    // height: 400,
    width: "95%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    zIndex: 10,
    padding: 8,
    marginTop: 20,
    alignSelf: "center",
  },
  input_section: {
    height: "100%",
    width: "100%",
    textAlignVertical: "top",
    fontFamily: "Poppins-Regular",
    fontSize: 14,
    color: "white",
  },
  ts_text: {
    fontSize: 20,
    fontFamily: "Poppins-Medium",
    color: "white",
    textAlign: "center",
    marginTop: 10,
  },
  pg_text: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    marginTop: 20,
    color: "white",
    paddingLeft: 10,
  },
  pg_section: {
    height: 170,
    width: "100%",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginTop: 5,
    padding: 5,
    position: "relative",
    overflow: "visible",
  },
  pg_section_large: {
    height: 360,
    width: "100%",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginTop: 5,
    padding: 5,
  },
  pg_section_large_large: {
    height: 400,
    width: "100%",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginTop: 5,
    padding: 5,
  },
  pg_section_ava: {
    // height: 250,
    width: "100%",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginTop: 5,
    padding: 5,
    display: "flex",
    gap: 10,
  },
  line: {
    height: 1,
    width: "98%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    alignSelf: "center",
  },
  pg_s_top: {
    // height: "fit-conent",
    width: "100%",
    marginBottom: 20,
    position: "relative",
    overflow: "visible",
  },
  pg_s_top_large: {
    height: "70%",
    width: "100%",
    marginBottom: 20,
  },
  pg_s_bottom: {
    height: "40%",
    width: "100%",
    padding: 5,
  },
  section_cut_view: {
    height: 20,
    width: 20,
    borderRadius: 50,
    borderColor: "#ffffff70",
    position: "absolute",
    right: -13,
    top: -13,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  sa_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
    marginTop: 5,
  },
  date_time_section_d: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  date_time_section_d_ava: {
    height: 40,
    width: "38%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  av_svg: {
    position: "absolute",
    left: 10,
  },
  date_time_section_t: {
    height: 40,
    width: "48%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  date_time_section_t_ava: {
    height: 40,
    width: "45%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  dt_text: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "white",
    textAlign: "flex-start",
    width: "75%",
    // backgroundColor: "red",
  },
  dt_text_100: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "white",
    textAlign: "flex-start",
    width: "100%",
    textAlign: "center",
    // backgroundColor: "red",
  },
  dt_text_d: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "white",
    textAlign: "flex-start",
    width: "70%",
    // backgroundColor: "red",
  },
  dt_whole_section: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 10,
    marginTop: 10,
  },
  dt_whole_section_ava: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 10,
  },
  btp_section: {
    height: 40,
    width: "100%",
    padding: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  discount_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    padding: 10,
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
  },
  btp_text: {
    fontSize: 14,
    color: "#ffffff",
    fontFamily: "Poppins-Regular",
  },
  oval: {
    height: 35,
    // width: "fit-content",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    paddingLeft: 12,
    paddingRight: 12,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  oval_large: {
    height: 30,
    // width: "fit-content",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    paddingLeft: 15,
    paddingRight: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  oval_text: {
    fontSize: 13,
    color: "white",
    verticalAlign: "center",
    textAlign: "center",
    fontFamily: "Poppins-Regular",
  },
  amount_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
  },
  input_whole_section_btn_time: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 0,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  bs_whole_view: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    gap: 10,
    // backgroundColor: "red",
  },
  bs_whole_view_cal: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    gap: 10,
    marginTop: 20,
    // backgroundColor: "red",
  },
  country_scroll: {
    width: "100%",
    height: "100%",
  },
  last_empty_space_rb: {
    height: 30,
    width: "100%",
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
  },
  calendar: {
    width: screenWidth - 20,
    borderRadius: 6,
    height: 340,
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text_section_flag: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    marginRight: 10,
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
  },
  bs_input: {
    height: "100%",
    width: "60%",
    paddingLeft: 20,
    fontFamily: "Poppins-Regular",
    color: "#ffffff",
  },
  v_line: {
    height: "40%",
    width: 1,
    backgroundColor: "#ffffff60",
    borderRadius: 50,
  },
  min_section: {
    height: "100%",
    // width: "15%",
    display: "flex",
    justifyContent: "center",
    paddingLeft: 15,
    paddingRight: 15,
  },
  min_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  circle: {
    height: 50,
    width: 50,
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 1)",
    marginLeft: 10,
  },
  price_ti: {
    height: "130%",
    minWidth: 20,
    fontSize: 12,
    color: "white",
    overflow: "visible",
    fontFamily: "Poppins-Regular",
  },
  check_to: {
    height: 40,
    width: 40,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "white",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
  },
  oi_dot_section_empty: {
    height: 0,
    width: 20,
  },
  oi_empty_section: {
    height: "100%",
    width: "10%",
  },
});
export default styles;
