import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    marginTop: 20,
  },
  main_view: {
    height: "60%",
    width: "100%",
    zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    width: "100%",
  },
  //   starts here
  search_section_whole: {
    height: 50,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 30,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  search_section: {
    width: "85%",
    height: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 50,
    zIndex: 10,
  },
  filter_section: {
    height: 50,
    width: 50,
    borderRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  finter_section_in: {
    height: "97%",
    width: "96%",
    borderRadius: 20,
    backgroundColor: "rgba(51, 80, 148, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  search_section_input: {
    height: "100%",
    width: "100%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
  },
  search_svg_section: {
    height: "100%",
    width: "20%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  serach_input_section: {
    height: "100%",
    width: "80%",
  },
  sis_input: {
    height: "100%",
    width: "100%",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  indi_options: {
    height: 60,
    width: "100%",
    // marginTop: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  indi_option_text_section: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    // backgroundColor: "red",
  },
  indi_option_per_section: {
    height: "100%",
    width: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "green",
  },
  indi_option_svg_section: {
    height: "100%",
    width: "20%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "blue",
    gap: 27,
  },
  iots_text: {
    fontSize: 17,
    fontWeight: "400",
    letterSpacing: 0.7,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
