import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    position: "fixed",
    // backgroundColor: "red",
    top: 0,
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_2_: {
    height: 40,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue_: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  main_content_section: {
    height: "fit-content",
    width: "100%",
    paddingLeft: 20,
    paddingRight: 30,
    marginTop: 5,
  },
  title_section: {
    height: "fit-content",
    width: "100%",
    marginTop: 10,
    marginBottom: 6,
  },
  title: {
    fontSize: 15,
    fontFamily: "Poppins-Medium",
    color: "white",
    letterSpacing: 0.7,
  },
  list_title: {
    fontSize: 15,
    fontFamily: "Poppins-Regular",
    color: "white",
    letterSpacing: 0.7,
  },
  des_section: {
    height: "fit-content",
    width: "100%",
    marginBottom: 15,
  },
  des: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffffb9",
    letterSpacing: 0.7,
  },
  list_title_section: {
    height: "fit-content",
    width: "100%",
    marginBottom: 4,
  },
  des: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffffb9",
    letterSpacing: 0.7,
  },
  list_item_indi: {
    height: "fit-content",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    gap: 6,
    marginBottom: 5,
  },
  lii_dot_section: {
    height: "100%",
    width: "4%",
    alignItems: "center",
    paddingTop: 7,
  },
  dot: {
    height: 6,
    width: 6,
    backgroundColor: "#ffffff70",
    borderRadius: 50,
  },
  list_item_text: {
    fontSize: 14,
    color: "#ffffffb9",
    fontFamily: "Poppins-Regular",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Medium",
  },
});
export default styles;
