import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
  },
  //   starts here
  search_section_whole: {
    height: 50,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 30,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  search_section: {
    width: "70%",
    height: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 50,
  },
  filter_section: {
    height: 50,
    width: 50,
    borderRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  finter_section_in: {
    height: "97%",
    width: "96%",
    borderRadius: 20,
    backgroundColor: "rgba(51, 80, 148, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  search_section_input: {
    height: "100%",
    width: "100%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
  },
  search_svg_section: {
    height: "100%",
    width: "20%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  serach_input_section: {
    height: "100%",
    width: "80%",
  },
  sis_input: {
    height: "100%",
    width: "100%",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  sv_main: {
    height: 620,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 20,
    zIndex: 10,
  },
  indi_profile: {
    height: "100%",
    width: 325,
    // backgroundColor: "green",
    borderRadius: 20,
    overflow: "hidden",
    marginRight: 20,
  },
  start_view: {
    height: "100%",
    width: 30,
  },
  profile_img_Section: {
    height: "40%",
    width: "100%",
    backgroundColor: "red",
    position: "relative",
  },
  profile_img: {
    height: "100%",
    width: 325,
    objectFit: "cover",
  },
  bottom_section: {
    height: "60%",
    width: "100%",
  },
  name_rate_section: {
    height: 60,
    width: "100%",
    justifyContent: "center",
    fontFamily: "Poppins-Regular",
    alignItems: "center",
  },
  egl_section: {
    height: 25,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
  },
  egl_section_story: {
    height: "fit-content",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "green",
    alignItems: "center",
    // paddingLeft: 12,
    paddingTop: 5,
    // paddingRight: 12,
  },
  egl_section_: {
    height: 25,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
  },
  egl_section_af: {
    height: 130,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "green",
    alignItems: "center",
  },
  about_Section: {
    width: "100%",
    // backgroundColor: "blue",
    paddingLeft: 15,
    paddingRight: 15,
    marginTop: 15,
  },
  btn_section_: {
    height: 50,
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginTop: 20,
  },
  about_text: {
    fontSize: 13,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "300",
    fontFamily: "Poppins-Regular",
  },
  btn: {
    height: "75%",
    width: "45%",
    backgroundColor: "rgba(181, 195, 227, 0.1)",
    borderRadius: 60,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },

  btn_l: {
    height: "75%",
    paddingLeft: 15,
    paddingRight: 15,
    backgroundColor: "white",
    borderRadius: 60,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  btn_text: {
    fontSize: 12,
    color: "rgba(30, 63, 142, 1)",
    letterSpacing: 0.7,
    textAlign: "center",
    fontFamily: "Poppins-Regular",
  },
  name_rate: {
    height: "100%",
    width: "100%",
    // backgroundColor: "green",
    display: "flex",
    paddingLeft: 10,
    paddingRight: 10,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bia_section: {
    height: "30%",
    width: "100%",
    // backgroundColor: "green",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 10,
    paddingRight: 10,
    alignItems: "flex-start",
  },
  rate_section: {
    height: "100%",
    width: "30%",
    borderRadius: 80,
    backgroundColor: "rgba(181, 195, 227, 0.1)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    alignItems: "center",
    position: "absolute",
    top: 12,
    right: 10,
  },
  name: {
    // height: "100%",
    width: "fit-content",
    fontSize: 21,
    color: "white",
    fontFamily: "Poppins-Medium",
  },
  rate_text: {
    fontSize: 16,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "500",
  },
  bia_text: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.7)",
    letterSpacing: 0.7,
  },
  indi_egl: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    // paddingLeft: 10,
    // paddingRight: 10,
    width: "fit-content",
  },
  indi_egl_story: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
    paddingLeft: 10,
    paddingRight: 10,
    width: "fit-content",
  },
  egl_key: {
    fontSize: 12,
    fontWeight: "300",
    color: "rgba(255, 255, 255, 0.49)",
    letterSpacing: 0.7,
    width: "fit-content",
    fontFamily: "Poppins-Regular",
  },
  egl_value: {
    fontSize: 15,
    color: "white",
    letterSpacing: 0.7,
    width: "fit-content",
    fontFamily: "Poppins-Regular",
  },
  egl_value_key: {
    fontSize: 17,
    color: "white",
    letterSpacing: 0.7,
    width: "fit-content",
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
  },
  empty_space_for_key: {
    height: 10,
  },
  all_btns: {
    height: 40,
    width: "90%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "center",
  },
  indi_btn: {
    height: "100%",
    paddingLeft: 15,
    paddingRight: 15,
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
  },
  indi_btn_active: {
    height: "100%",
    paddingLeft: 15,
    paddingRight: 15,
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },

  indi_btn_tp: {
    height: 30,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    justifyContent: "center",
  },
  indi_btn_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  indi_btn_text_tp: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  price_time_section: {
    height: "fit-content",
    marginTop: 10,
    width: "100%",
    alignSelf: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    marginLeft: 10,
    marginRight: 10,
  },
  price_time_section_story: {
    height: "fit-content",
    marginTop: 10,
    width: "90%",
    alignSelf: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    padding: 10,
  },
  pg_text_v: {
    fontFamily: "Poppins-Medium",
    fontSize: 16,
    color: "white",
    // paddingLeft: 10,
    marginTop: 15,
    width: "100%",
    textAlign: "center",
  },
  pg_text: {
    fontFamily: "Poppins-Regular",
    fontSize: 13,
    color: "white",
    // paddingLeft: 10,
    marginTop: 15,
  },
  pg_text_pg: {
    fontFamily: "Poppins-Regular",
    fontSize: 12,
    color: "#ffffff90",
    // paddingLeft: 10,
    marginTop: 15,
  },
  pg_text_tp: {
    fontFamily: "Poppins-Regular",
    fontSize: 13,
    color: "white",
    // paddingLeft: 10,
    marginRight: 10,
  },
  tp_section: {
    height: 50,
    width: "100%",
    paddingRight: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // backgroundColor: "red",
  },
  empty_section: {
    height: 50,
    width: "100%",
  },
  dot_section: {
    height: 10,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    position: "absolute",
    bottom: 10,
    // backgroundColor: "red",
    flexDirection: "row",
  },
  dot: {
    height: 6,
    width: 6,
    borderRadius: 50,
    backgroundColor: "white",
  },
  dot_unactive: {
    height: 6,
    width: 6,
    borderRadius: 50,
    backgroundColor: "#ffffff70",
  },
  save_coach_btn: {
    height: 40,
    width: 40,
    borderRadius: 50,
    backgroundColor: "rgba(46, 45, 45, 0.15)",
    position: "absolute",
    top: 10,
    right: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.48)",
    backdropFilter: "blur(10px)",
  },

  save_coach_btn_share: {
    height: 40,
    width: 40,
    borderRadius: 50,
    backgroundColor: "rgba(46, 45, 45, 0.15)",
    position: "absolute",
    top: 60,
    right: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.48)",
    backdropFilter: "blur(10px)",
  },

  save_coach_btn_b: {
    height: 40,
    width: 40,
    borderRadius: 50,
    backgroundColor: "rgba(46, 45, 45, 0.15)",
    position: "absolute",
    top: 10,
    left: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.48)",
    backdropFilter: "blur(10px)",
  },
  bs_2_line: {
    height: 60,
    width: "90%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    // marginTop: 10,
    // backgroundColor: "red",
  },
  no_coach_section: {
    height: 400,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 50,
  },
  no_coach_text: {
    fontSize: 16,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "500",
    fontFamily: "Poppins-Regular",
    textAlign: "center",
  },
  loading_whole: {
    height: screenHeight - 300,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  rating_section: {
    height: 40,
    width: 80,
    borderRadius: 100,
    backgroundColor: "#ffffff10",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  rating_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  connection_box: {
    height: "fit-content",
    padding: 5,
    borderWidth: 1,
    borderColor: "#ffffff10",
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 8,
    paddingLeft: 10,
  },
});
export default styles;
