import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    gap: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "12%",
    // backgroundColor: "green",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "12%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 22,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
  },
  // starts here
  main_section: {
    height: "fit-content",
    width: "90%",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
    paddingBottom: 10,
  },
  table_head: {
    height: 80,
    width: "100%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  table_head_indi: {
    height: "100%",
    width: "25%",
    // backgroundColor: "green",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 6,
    paddingRight: 6,
  },
  thi_text: {
    textAlign: "center",
    fontSize: 11,
    color: "white",
    letterSpacing: 0.7,
  },
  table_line: {
    height: 1,
    width: "94%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    alignSelf: "center",
  },
  table_indi_row: {
    height: 60,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
  },
  td: {
    height: "100%",
    width: "25%",
    // backgroundColor: "green",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  td_text: {
    fontSize: 14,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "400",
  },
  dot: {
    height: 15,
    width: 15,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 100,
  },
});
export default styles;
