import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_Section: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 22,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
  },
  main_event: {
    width: "86%",
    // height: "fit-content",
    maxHeight: 600,
    // backgroundColor: "red",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
    paddingBottom: 2,
    // paddingTop: 2,
  },
  indi_event_img_section: {
    height: 160,
    width: "94%",
    backgroundColor: "red",
    alignSelf: "center",
    marginTop: 8,
    marginBottom: 10,
    borderRadius: 15,
    overflow: "hidden",
  },
  ie_img: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
  },
  indi_events_bottom: {
    height: 140,
    width: "97%",
    alignSelf: "center",
    display: "flex",
    flexDirection: "row",
  },
  ie_left: {
    height: "100%",
    width: "65%",
    display: "flex",
    // backgroundColor: "red",
  },
  ie_right: {
    height: "100%",
    width: "35%",
    // backgroundColor: "green",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  ie_left_event_name_view: {
    // height: "fit-content",
    // width: "fit-content",
  },
  event_name: {
    fontSize: 18,
    color: "white",
    fontWeight: "400",
    paddingLeft: 10,
    marginTop: 10,
    letterSpacing: 0.7,
    // backgroundColor: "green",
    fontFamily: "Poppins-Regular",
  },
  hosted_by: {
    fontSize: 16,
    color: "#ffffff90",
    // fontWeight: "400",
    paddingLeft: 10,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    // backgroundColor: "green",
  },
  ie_time_section: {
    display: "flex",
    flexDirection: "row",
    paddingLeft: 10,
    marginTop: 10,
    gap: 8,
    alignItems: "center",
    // backgroundColor: "red",
  },
  event_time: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    textTransform: "capitalize",
  },
  event_date_section: {
    height: 80,
    width: 70,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  event_date: {
    fontSize: 16,
    color: "white",
  },
  about_the_workshop_section: {
    width: "97%",
    // height: "fit-content",
    marginBottom: 20,
  },
  atw_title: {
    fontSize: 18,
    letterSpacing: 0.7,
    paddingLeft: 10,
    color: "white",
  },
  atw_des: {
    fontSize: 14,
    letterSpacing: 0.7,
    paddingLeft: 10,
    color: "rgba(255, 255, 255, 0.7)",
    marginTop: 6,
    fontWeight: "300",
    // verticalAlign: "center",
  },
  li: {
    fontSize: 14,
    letterSpacing: 0.7,
    paddingLeft: 5,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "300",
    // marginTop: 6,
    // verticalAlign: "center",
  },
  dot: {
    height: 5,
    width: 5,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    // marginRight: 6,
  },
  ul: {
    width: "100%",
    paddingLeft: 10,
    marginTop: 5,
    display: "flex",
    flexDirection: "row",
  },
  ul_text_section: {
    display: "flex",
    // alignItems: "center",
    // backgroundColor: "red",
  },
  dot_section: {
    width: 10,
    // height: "fit-content",
    // backgroundColor: "green",
    display: "flex",
    // justifyContent: "center",
    alignItems: "center",
    paddingTop: 7,
  },
  book_now_btn_section: {
    width: "86%",
    height: 60,
    backgroundColor: "white",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bn_text: {
    fontSize: 16,
    color: "rgba(15, 28, 78, 1)",
    textAlign: "center",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
