import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
const screenHeight = Dimensions.get("window").height;
const screenWidth = Dimensions.get("window").width;
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_Section: {
    height: 20,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    marginBottom: 20,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  //   starts here
  search_section_whole: {
    height: 50,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  search_section: {
    width: "86%",
    height: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 50,
  },
  filter_section: {
    height: 50,
    width: 50,
    borderRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  finter_section_in: {
    height: "97%",
    width: "96%",
    borderRadius: 20,
    backgroundColor: "rgba(51, 80, 148, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  search_section_input: {
    height: "100%",
    width: "100%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
  },
  search_svg_section: {
    height: "100%",
    width: "20%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  serach_input_section: {
    height: "100%",
    width: "80%",
  },
  sis_input: {
    height: "100%",
    width: "100%",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  banner_space_Section: {
    height: 120,
    width: "86%",
    alignSelf: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 20,
    overflow: "hidden",
    position: "relative",
  },
  ad_text_section: {
    height: 30,
    width: 45,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "absolute",
    right: 8,
    top: 8,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  ad_text: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.5)",
    textAlign: "center",
    fontWeight: "500",
  },
  h_sv_outer: {
    height: 60,
    width: "100%",
    marginBottom: 20,
  },
  options_sv: {
    height: "100%",
    width: "100%",
    marginTop: 10,
    display: "flex",
    alignItems: "center",
    flex: 1,
  },
  indi_options: {
    height: 40,
    width: "fit-content",
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginRight: 10,
  },
  indi_o_text: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 18,
    letterSpacing: 0.7,
  },
  hsv_left_section: {
    height: "100%",
    width: "7%",
  },
  indi_event: {
    height: 250,
    width: screenWidth - 40,
    // backgroundColor: "red",
    alignSelf: "center",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 15,
  },
  indi_event_b2: {
    height: 250,
    width: screenWidth - 70,
    // backgroundColor: "red",
    alignSelf: "center",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 15,
  },
  indi_events_top: {
    height: "50%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  indi_event_img: {
    height: "95%",
    width: "97%",
    alignSelf: "center",
    borderRadius: 16,
  },
  indi_events_bottom: {
    height: "50%",
    width: "97%",
    alignSelf: "center",
    display: "flex",
    flexDirection: "row",
  },
  ie_left: {
    height: "100%",
    width: "65%",
    // backgroundColor: "red",
  },
  ie_right: {
    height: "100%",
    width: "35%",
    // backgroundColor: "green",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  ie_left_event_name_view: {
    height: "fit-content",
    width: "fit-content",
  },
  event_name: {
    fontSize: 18,
    color: "white",
    fontWeight: "400",
    paddingLeft: 5,
    marginTop: 10,
    fontFamily: "Poppins-Regular",
  },
  ie_time_section: {
    display: "flex",
    flexDirection: "row",
    paddingLeft: 5,
    marginTop: 10,
    gap: 8,
    alignItems: "center",
  },
  event_time: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  event_date_section: {
    height: 70,
    width: 70,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  event_date: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  empty_section: {
    height: 70,
    width: "100%",
  },
  main_view: {
    zIndex: 100,
  },
  indi_b2_sv: {},
  first_es: {
    height: "100%",
    // width: 20,
  },
  no_events: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  whole_events: {
    height: "100%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
});
export default styles;
