import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  welcome_view: {
    // height: "fit-content",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
  },
  welcome_text: {
    fontSize: 30,
    color: "white",
    fontWeight: "400",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    textAlign: "center",
    width: "100%",
  },
  welcome_des: {
    width: "100%",
    fontSize: 18,
    color: "#ffffffa1",
    fontSize: 16,
    fontWeight: "300",
    // marginTop: 5,
    textAlign: "center",
    fontFamily: "Poppins-Regular",
  },
  otp_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
  },
  otp_indi: {
    height: 50,
    width: 50,
    borderRadius: "50%",
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    overflow: "hidden",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_lg: {
    height: 50,
    width: 50,
    borderRadius: "50%",
  },
  oi_input: {
    height: "100%",
    width: "100%",
    textAlign: "center",
    color: "white",
    fontSize: 20,
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_3: {
    height: "100%",
    width: "23%",
  },
  bs_1_circle: {
    height: 55,
    width: 55,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "#ffffff90",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  fp_whole: {
    width: "100%",
    // height: "fit-content",
    display: "flex",
    alignItems: "center",
    marginBottom: 10,
    // marginTop: 30,
  },
  fp_inner: {
    width: "85%",
    // height: "fit-content",
    display: "flex",
    justifyContent: "flex-end",
    zIndex: 10,
  },
  fp_text: {
    textAlign: "right",
    color: "#ffffff90",
    letterSpacing: 1,
    textDecorationColor: "#ffffff90",
    textDecorationLine: "underline",
  },
  fp_text_center: {
    width: "100%",
    textAlign: "center",
    color: "#ffffff90",
    letterSpacing: 1,
    fontFamily: "Poppins-Medium",
    // textDecorationColor: "#ffffff90",
    // textDecorationLine: "underline",
  },
  su_text: {
    color: "white",
    textDecorationLine: "underline",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    // marginTop: 330,
    zIndex: 10000,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    fontFamily: "Poppins-Regular",
    color: "#0F1C4E",
  },
});
export default styles;
