import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    // alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  byp_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  percent_section: {
    height: 200,
    width: "90%",
    marginVertical: 30,
    borderRadius: 20,
    overflow: "hidden",
    alignSelf: "center",
  },
  bankdetail_section: {
    alignSelf: "center",
    height: 300,
    width: "90%",
    marginTop: 30,
    borderRadius: 20,
    overflow: "hidden",
  },
  ps_inner: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  bd_inner: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  ps_top_section: {
    height: "40%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bd_top_section: {
    height: "20%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    paddingLeft: 20,
  },
  ps_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  bd_text: {
    fontSize: 18,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  ps_ips: {
    height: "60%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  percent_ps: {
    height: 35,
    width: 80,
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    flexDirection: "row",
    paddingLeft: 12,
    paddingRight: 12,
    gap: 10,
  },
  percent_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  ps_member: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  ps_ips_indi_section: {
    height: "100%",
    width: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bank_details_inner: {
    height: "75%",
    width: "90%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    alignSelf: "center",
    borderRadius: 20,
    justifyContent: "space-around",
    padding: 10,
  },
  bd_details_text_view: {
    // marginTop: 10,
    // paddingLeft: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  bd_details_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 60,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  banking_info_input: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
    width: "100%",
    height: "100%",
  },
  bs_whole_view: {
    height: "100%",
    alignItems: "center",
    gap: 10,
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  nobill: {
    textAlign: "center",
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
  noHistoryContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
export default styles;
