import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 22,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
  },
  //   starts here
  full_indicator: {
    width: "86%",
    height: 10,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 10,
    overflow: "hidden",
  },
  indicator_inside: {
    height: "100%",
    width: "15%",
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: 10,
  },
  question_section: {
    height: 150,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  question_text: {
    fontSize: 24,
    textAlign: "center",
    fontWeight: "400",
    letterSpacing: 0.7,
    color: "white",
    width: "80%",
  },
  indi_answer_section: {
    display: "flex",
    alignSelf: "center",
    width: "86%",
    height: 75,
    borderRadius: 100,
    marginBottom: 10,
    flexDirection: "row",
  },
  q_dot_section: {
    height: 75,
    width: 75,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  dot: {
    height: 25,
    width: 25,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  question_outer: {
    zIndex: 100,
  },
  answer_section: {
    height: "100%",
    width: "75%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 30,
  },
  answer_text: {
    fontSize: 18,
    color: "white",
    letterSpacing: 1,
    fontWeight: "400",
  },
});

export default styles;
