import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "15%",
  },
  bs_2: {
    height: "100%",
    width: "55%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "#ffffff",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  bs_2_cue_m: {
    textAlign: "center",
    fontSize: 16,
    color: "#ffffff90",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  //   starts here
  full_indicator: {
    width: "86%",
    height: 5,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    alignSelf: "center",
    marginTop: 5,
    borderRadius: 10,
    overflow: "hidden",
  },
  indicator_inside: {
    height: "100%",
    width: "15%",
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: 10,
  },
  question_section: {
    height: 190,
    width: "100%",
    // backgroundColor: "red",
    // marginTop: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  question_text: {
    fontSize: 20,
    textAlign: "center",
    fontWeight: "400",
    letterSpacing: 0.7,
    color: "white",
    width: "80%",
    fontFamily: "Poppins-Regular",
    marginTop: 10,
    marginBottom: 10,
  },
  indi_answer_section: {
    display: "flex",
    alignSelf: "center",
    width: "86%",
    height: 60,
    borderRadius: 100,
    marginBottom: 10,
    flexDirection: "row",
  },
  q_dot_section: {
    height: 60,
    width: 75,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  dot: {
    height: 25,
    width: 25,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  active_dot: {
    height: "70%",
    width: "70%",
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: 100,
  },
  question_outer: {
    zIndex: 100,
  },
  answer_section: {
    height: "100%",
    width: "75%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 30,
  },
  answer_text: {
    fontSize: 16,
    color: "white",
    letterSpacing: 1,
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
  },
  ai_section: {
    height: "70%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  question_number: {
    fontSize: 17,
    color: "#ffffff90",
    fontFamily: "Poppins-Regular",
  },
  bs_2_line: {
    height: 60,
    width: "90%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
    // backgroundColor: "red",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    // marginTop: 5,
  },
  input_whole_section_btn_dull: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    // marginTop: 5,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  input_inner_section_btn_dull: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    // borderWidth: 1.2,
    // borderColor: "rgba(244, 244, 244, 0.1)",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(244, 244, 244, 0.1)",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  login_text_dull: {
    fontSize: 18,
    color: "#ffffff",
    fontFamily: "Poppins-Regular",
  },
  msv: {
    zIndex: 10,
  },
});

export default styles;
