import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "54%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  bs_2_cue_m: {
    textAlign: "center",
    fontSize: 16,
    color: "#ffffff90",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  option_section: {
    height: 50,
    width: "86%",
    // backgroundColor: "red",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: "rgba(194, 201, 220, 0.1)",
    flexDirection: "row",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    // gap: 10,
    zIndex: 100,
  },
  option_section_inner: {
    height: "100%",
    width: "100%",
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: "rgba(194, 201, 220, 0.1)",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  option_section_inner_wob: {
    height: "100%",
    width: "100%",
    // borderRadius: 100,
    // borderWidth: 1.5,
    // borderColor: "rgba(194, 201, 220, 0.1)",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  option_section_outer: {
    height: "90%",
    width: "48%",
    // borderRadius: 100,
    // borderWidth: 1.5,
    // borderColor: "rgba(194, 201, 220, 0.1)",
    // flexDirection: "row",
    // justifyContent: "center",
    // alignItems: "center",
    // gap: 10,
    overflow: "hidden",
    zIndex: 10,
  },
  osi_svg_section: {
    height: "100%",
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  osi_text_Section: {
    height: "100%",
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    // backgroundColor: "green",
  },
  osi_text: {
    width: "fit-content",
    fontSize: 17,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "400",
    fontFamily: "Poppins-Regular",
  },
  main_content_section: {
    width: "86%",
    height: "72%",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
    padding: 20,
    paddingTop: 2,
    paddingBottom: 2,
    zIndex: 100,
  },
  main_content_text: {
    fontSize: 17,
    color: "#ffffff",
    letterSpacing: 0.7,
    marginBottom: 25,
    fontFamily: "Poppins-Regular",
    // marginTop: 5,
  },
  main_content_text_guide: {
    fontSize: 17,
    color: "#ffffff",
    letterSpacing: 0.7,
    marginBottom: 25,
    fontFamily: "Poppins-Regular",
    marginTop: 5,
  },
  empty_section: {
    height: 100,
    width: "100%",
  },
  top_empty_section: {
    height: 20,
    width: "100%",
  },
  scroll_view: {
    position: "relative",
  },
  dark_side: {
    height: 20,
    width: "100%",
    position: "fixed",
    top: 0,
    left: 0,
  },
  main_content_question: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    // marginBottom: 2,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Medium",
  },
  main_content_question_para: {
    fontSize: 16,
    fontWeight: "400",
    color: "#ffffff50",
    marginBottom: 4,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  bs_2_line: {
    height: 60,
    width: "90%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
    // backgroundColor: "red",
  },
});
export default styles;
