import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 14,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  main_agreement_section: {
    height: 50,
    width: "90%",
    alignSelf: "center",
    borderRadius: 10,
    marginBottom: 20,
  },
  main_agreement_section_content: {
    height: "fit-content",
    width: "90%",
    alignSelf: "center",
    borderRadius: 10,
    marginBottom: 20,
    position: "relative",
    overflow: "visible",
    minHeight: 150,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  main_agreement_section_content_title: {
    height: "fit-content",
    width: "90%",
    alignSelf: "center",
    borderRadius: 10,
    marginBottom: 20,
    position: "relative",
    overflow: "visible",
    minHeight: 80,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  add_btn: {
    height: 50,
    // paddingLeft: 20,
    // paddright: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
    zIndex: 100,
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 10,
  },
  mas_inner: {
    height: "100%",
    // width: "100%",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
    overflow: "visible",
  },
  mas_input: {
    height: "fit-content",
    minHeight: 150,
    width: "100%",
    padding: 10,
    verticalAlign: "top",
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
  mas_input_title: {
    height: "fit-content",
    minHeight: 80,
    width: "100%",
    padding: 10,
    verticalAlign: "top",
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
    zIndex: 10,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 14,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  add_btn_view: {
    marginTop: 20,
    paddingLeft: 20,
    paddingRight: 20,
    width: "fit-content",
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  add_btn_text: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.5,
    color: "white",
  },
  cut_circle: {
    height: 30,
    width: 30,
    borderRadius: 100,
    backgroundColor: "#ffffff",
    position: "absolute",
    right: 5,
    top: 5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  rich_toolbar: {
    position: "absolute",
    bottom: 0,
    width: "107%",
    left: 0,
    backgroundColor: "transparent",
    color: "white",
  },
  label: {
    fontSize: 12,
    color: "white",
    paddingLeft: 25,
    paddingBottom: 5,
  },
  empty_space: {
    height: 300,
    width: "100%",
    backgroundColor: "transparent",
  },
  main_recommend_section: {
    width: "100%",
    height: "fit-content",
    paddingLeft: 18,
    paddingRight: 18,
    marginTop: 20,
  },
  sample_text: {
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  gray: {
    color: "#ffffff90",
    fontFamily: "Poppins-Regular",
    fontSize: 14,
  },
  space: {
    height: 15,
    width: "100%",
  },
});
export default styles;
