import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    marginTop: 20,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  user_msg: {
    width: "100%",
    paddingLeft: 20,
    display: "flex",
    marginBottom: 20,
  },
  me_msg: {
    width: "100%",
    paddingRight: 20,
    display: "flex",
    alignItems: "flex-end",
    marginBottom: 20,
  },
  a_user_msg: {
    padding: 15,
    width: "90%",
    backgroundColor: "#5264A5",
    borderRadius: 10,
    borderBottomLeftRadius: 0,
  },
  a_me_msg: {
    padding: 15,
    width: "90%",
    backgroundColor: "#009DFF",
    borderRadius: 10,
    borderBottomRightRadius: 0,
  },
  me_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  user_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  time: {
    fontSize: 14,
    color: "#ffffff60",
    marginTop: 10,
  },
  input_Section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    zIndex: 10,
    marginTop: 10,
  },
  input_inner: {
    height: "100%",
    width: "90%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    position: "relative",
  },
  input: {
    height: "100%",
    width: "100%",
    paddingLeft: 20,
    color: "white",
    fontSize: 14,
    fontFamily: "Poppins-Regular",
  },
  btn: {
    height: 50,
    width: 50,
    borderRadius: 50,
    backgroundColor: "#ffffff10",
    position: "absolute",
    right: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
});
export default styles;
