import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    // justifyContent: "center",
    // backgroundColor: "red",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  byp_text: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  input_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
  },

  input_inner_section: {
    height: "fit-content",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    // overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },

  input_inner_section_btn_cat: {
    height: "100%",
    width: "92%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  svg_circle: {
    height: 60,
    width: 40,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  svg_circle_eye: {
    height: 60,
    width: 60,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },

  input_section: {
    height: "100%",
    width: 210,
    // backgroundColor: "green",
  },
  input_section_nsvg: {
    height: "100%",
    width: 210,
    paddingLeft: 20,
    // backgroundColor: "green",
  },
  input_section_text: {
    height: "100%",
    width: 180,
    display: "flex",
    justifyContent: "center",
  },
  input_section_text_nsvg: {
    height: "fit-content",
    width: 220,
    display: "flex",
    justifyContent: "center",
    paddingLeft: 20,
  },
  input_section_text_nsvg_small: {
    height: "100%",
    // width: ,
    display: "flex",
    justifyContent: "center",
    paddingLeft: 20,
  },
  input: {
    height: "100%",
    width: "100%",
    letterSpacing: 1,
    fontSize: 14,
    color: "white",
    // fontFamily: "Poppins-Regular",
    // paddingBottom: 0,
    // backgroundColor: "red",
    overflow: "hidden",
  },
  input_text: {
    letterSpacing: 1,
    fontSize: 14,
    color: "#ffffff90",
    paddingLeft: 6,
    // textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
  },
  input_text_small: {
    letterSpacing: 1,
    fontSize: 14,
    color: "#ffffff90",
    paddingLeft: 6,
    textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
    width: "fit-content",
    // backgroundColor: "blue",
  },
  input_text_active: {
    letterSpacing: 1,
    fontSize: 14,
    color: "#ffffff",
    paddingLeft: 6,
    // textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
    height: "fit-content",
  },
  input_text_active_level: {
    letterSpacing: 1,
    fontSize: 12,
    color: "#ffffff",
    paddingLeft: 6,
    textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
  },
  input_text_active_small: {
    letterSpacing: 1,
    fontSize: 12,
    color: "#ffffff",
    paddingLeft: 6,
    textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
  },
  top_empty_section: {
    height: 20,
    width: "100%",
  },
  label: {
    height: "100%",
    width: "70%",
    display: "flex",
    justifyContent: "center",
    // backgroundColor: "red",
  },
  label_text: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff80",
    paddingLeft: 4,
  },
  label_text_active: {
    letterSpacing: 1,
    fontSize: 16,
    color: "#ffffff",
    paddingLeft: 4,
  },
  bs_whole_view: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    gap: 10,
  },
  bs_whole_view_cat: {
    // height: "100%",
    width: "100%",
    gap: 10,
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    paddingLeft: 10,
    paddingRight: 10,
    // backgroundColor: "red",
  },
  empty_category_view: {
    height: 140,
    width: "100%",
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  fp_whole_text: {
    width: "85%",
    height: "fit-content",
    // backgroundColor: "green",
  },
  fp_whole_svg_section: {
    width: "10%",
    height: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    // backgroundColor: "red",
  },
  flag_svg: {
    height: 20,
    width: 20,
    borderRadius: 100,
    overflow: "hidden",
  },
  svg_view: {
    height: "fit-content",
    width: "fit-content",
    borderRadius: 100,
    overflow: "hidden",
  },
  cc_view: {
    height: "100%",
    widthL: "fit-content",
    display: "flex",
    justifyContent: "center",
  },
  cc_text: {
    fontSize: 16,
    color: "white",
    // fontWeight: 500,
  },
  drop_down_section: {
    height: "100%",
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
  },
  dd_svg: {
    height: 20,
    width: 20,
  },
  input_inner_section: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  svg_circle_cn: {
    height: 50,
    width: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 5,
  },
  svg_circle_eye: {
    height: 60,
    width: 60,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },
  small_dd: {
    height: "100%",
    width: "30%",
    // backgroundColor: "red",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  small_dd_inner: {
    height: 35,
    width: "95%",
    borderRadius: 50,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    gap: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  sdd_text: {
    fontSize: 10,
    color: "white",
    textAlign: "center",
  },
  dot: {
    height: 20,
    width: 20,
    borderRadius: 50,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  dot_active: {
    height: 20,
    width: 20,
    borderRadius: 50,
    backgroundColor: "#009DFF",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  input_whole_section_dot_text: {
    height: "fit-content",
    display: "flex",
    flexDirection: "row",
    width: "80%",
    gap: 10,
    alignSelf: "center",
    alignItems: "center",
  },
  dot_text: {
    fontSize: 12,
    color: "#ffffff",
    fontFamily: "Poppins-Regular",
  },
  indi_tag: {
    height: 45,
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    zIndex: 100,
  },
  indi_tag_active: {
    height: 45,
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    zIndex: 100,
    backgroundColor: "white",
  },
  indi_tag_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  indi_tag_text_active: {
    fontSize: 14,
    color: "rgba(30, 63, 142, 1)",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  cc_view_: {
    width: "100%",
    paddingLeft: 12,
    paddingRight: 10,
    // marginTop: 30,
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  cc_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  multiple_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  clt_label: {
    paddingLeft: 40,
    marginTop: 20,
    marginBottom: 10,
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
  },
});
export default styles;
