import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  top_Section: {
    height: 20,
    width: "100%",
    // backgroundColor: "red",
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 22,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
  },
  search_section_whole: {
    height: 50,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 30,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    marginBottom: 10,
  },
  search_section: {
    width: "70%",
    height: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 50,
  },
  filter_section: {
    height: 50,
    width: 50,
    borderRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  finter_section_in: {
    height: "97%",
    width: "96%",
    borderRadius: 20,
    backgroundColor: "rgba(51, 80, 148, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  search_section_input: {
    height: "100%",
    width: "100%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
  },
  search_svg_section: {
    height: "100%",
    width: "20%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  serach_input_section: {
    height: "100%",
    width: "80%",
  },
  sis_input: {
    height: "100%",
    width: "100%",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  options: {
    // height: 60,
    width: "100%",
    // backgroundColor: "red",
  },
  outer_h_sv: {
    height: 45,
    width: "100%",
    marginTop: 10,
  },
  indi_options: {
    paddingLeft: 20,
    paddingRight: 20,
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 100,
    marginRight: 10,
  },
  indi_option_text: {
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  left_ep: {
    height: "100%",
    width: 25,
  },
  main_sv: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    // backgroundColor: "red",
    justifyContent: "center",
    gap: 20,
    marginTop: 30,
  },
  indi_product: {
    height: 205,
    width: 150,
    // backgroundColor: "green",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  indi_p_img_section: {
    height: 90,
    width: "94%",
    // backgroundColor: "red",
    alignSelf: "center",
    borderRadius: 15,
    marginTop: 4,
    overflow: "hidden",
  },
  product_image: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
  },
  rate_p_section: {
    display: "flex",
    flexDirection: "row",
    marginTop: 8,
    paddingLeft: 8,
    gap: 10,
    alignItems: "center",
  },
  price_buy_section: {
    height: "20%",
    width: "100%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    marginTop: 8,
    paddingLeft: 4,
    paddingRight: 4,
  },
  product_name: {
    fontSize: 14,
    fontWeight: "400",
    letterSpacing: 0.7,
    paddingLeft: 6,
    paddingRight: 4,
    marginTop: 4,
    color: "white",
  },
  rate_text: {
    fontSize: 14,
    color: "white",
  },
  buy_now_btn: {
    height: 30,
    width: "55%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  buy_now_text: {
    fontSize: 12,
    color: "white",
  },
  price_cut: {
    color: "rgba(255, 255, 255, 0.5)",
    fontSize: 8,
    textAlign: "right",
    textDecorationLine: "line-through",
  },
  price: {
    color: "rgba(255, 255, 255, 1)",
    fontSize: 12,
    textAlign: "right",
  },
  price_section_whole: {
    width: "45%",
    height: "100%",
    paddingRight: 6,
  },
});
export default styles;
