import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "100%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    marginTop: 10,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 20,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  indi_banner_section: {
    height: 60,
    width: "90%",
    borderRadius: 50,
    alignSelf: "center",
    marginTop: 10,
  },
  indi_banner_section_n: {
    height: 200,
    width: "90%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 10,
  },
  indi_banner_section_large: {
    height: 120,
    width: "90%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 10,
  },
  indi_banner_section_large2: {
    height: 210,
    width: "90%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 10,
  },
  inner_ibs: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
  },
  inner_ibs_n: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    paddingTop: 6,
  },
  inner_ibs_sbs: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 20,
    paddingRight: 20,
  },
  inner_ibs_large: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    padding: 15,
  },
  inner_ibs_sb: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
    paddingRight: 20,
    justifyContent: "space-between",
  },
  iibs_text_input: {
    fontSize: 16,
    color: "#ffffff",
    height: "100%",
    width: "100%",
    fontFamily: "Poppins-Regular",
  },
  iibs_text_input_pl: {
    fontSize: 16,
    color: "#ffffff",
    height: "100%",
    width: "100%",
    fontFamily: "Poppins-Regular",
    paddingLeft: 10,
  },
  iibs_text: {
    fontSize: 16,
    color: "#ffffff",
    fontFamily: "Poppins-Regular",
  },
  dnt_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#ffffff80",
  },
  date_time_w_section: {
    marginTop: 20,
    width: "100%",
    height: 40,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  date_time_section_d: {
    height: 40,
    width: "42%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  date_time_section_t: {
    height: 40,
    width: "55%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  dt_text: {
    fontSize: 12,
    // fontFamily: "Poppins-Regular",
    color: "white",
  },
  dt_whole_section: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  dt_whole_section_b: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    // marginTop: 20,
  },
  dot_circle: {
    height: 15,
    width: 15,
    backgroundColor: "rgba(255, 255, 255, 0.19)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 10,
  },
  event_virtual_in_person: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  dc_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  ebt_price_section: {
    height: 40,
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  price_section: {
    height: "100%",
    width: "fit-content",
    paddingLeft: 17,
    paddingRight: 17,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  price_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  line: {
    height: "75%",
    width: 2,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
  },
  dicount_view: {
    height: "100%",
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  dicount_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  from_to_section: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
  },
  from_to_text_f: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
    width: "40%",
    textAlign: "center",
  },
  from_to_text_t: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "white",
    width: "60%",
    textAlign: "center",
  },
  des_ti: {
    verticalAlign: "top",
    height: "100%",
    width: "100%",
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Medium",
  },
});
export default styles;
