import { StyleSheet, Platform, StatusBar as sb } from "react-native";
const styles = StyleSheet.create({
  whole_tab: {
    height: 80,
    width: "100%",
    // backgroundColor: "red",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    position: "absolute",
    bottom: 0,
    overflow: "visible",
    paddingBottom: 14,
  },
  tab_back_view: {
    height: "100%",
    width: "100%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    overflow: "visible",
  },
  tab_back_upper: {
    height: "98%",
    width: "99.4%",
    // backgroundColor: "red",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: "row",
    position: "relative",
    overflow: "visible",
  },
  tab_indi: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    gap: 10,
    overflow: "visible",
    // backgroundColor: "red",
  },
  tab_indi_text: {
    textAlign: "center",
    color: "white",
    fontSize: 14,
    letterSpacing: 0.7,
    marginBottom: 5,
  },
  tab_indi_text_: {
    textAlign: "center",
    color: "white",
    fontSize: 14,
    letterSpacing: 0.7,
  },
  journal_whole: {
    // height: 60,
    // width: 60,
    // backgroundColor: "red",
    position: "absolute",
    bottom: 25,
    // right: 30,
    zIndex: 10,
    overflow: "visible",
    // transform: [{ rotateZ: "45deg" }],
    // borderRadius: 10,
    // overflow: "hidden",
  },
  jw_stroke: {
    height: "100%",
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  svg_section: {
    height: 20,
  },
  jw_inner: {
    height: "98%",
    width: "98%",
    borderRadius: 10,
  },
  svg_holder: {
    // backgroundColor: "red",
    height: 25,
    width: 25,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
});
export default styles;
