import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    flex: 1,
    // backgroundColor: "red",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "120%",
    width: "100%",
    position: "absolute",
    zIndex: -1,
    top: 0,
    left: 0,
    backgroundColor: "red",
    overflow: "visible",
  },
  backgroundImage: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
    flex: 1,
    overflow: "visible",
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  sv_oter: {
    height: "100%",
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: sb.currentHeight,
    width: "100%",
  },
  help_portion: {
    height: 60,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  hp1: {
    height: "100%",
    width: "20%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  hp2: {
    height: "100%",
    width: "60%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  hp3: {
    height: "100%",
    width: "20%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  h2_text: {
    fontSize: 22,
    fontWeight: "600",
    color: "#ffffff90",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Medium",
  },
  circle: {
    // backgroundColor: "red",
    height: 50,
    width: 50,
    borderRadius: 50,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    overflow: "hidden",
  },
  inner_circle: {
    height: "97%",
    width: "97%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(52, 79, 148, 1)",
    borderRadius: 50,
  },
  greeting_whole: {
    width: "100%",
    paddingLeft: 20,
    marginTop: 10,
    // backgroundColor: "red",
  },
  greeting_text: {
    fontSize: 23,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "400",
    marginBottom: 5,
    fontFamily: "Poppins-Regular",
    // backgroundColor: "blue",
    // width: "20%",
  },
  greeting_text1: {
    fontSize: 23,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "400",
    marginBottom: 5,
    marginRight: 5,
    // backgroundColor: "blue",
    // width: "20%",
    width: "fit-content",
    flexShrink: 1,
    textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
  },
  gt_svg: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    // width: "fit-content",
    // height: "auto",
    // flex: 1,
    // backgroundColor: "red",
  },
  indi_acr_section: {
    height: 180,
    width: "92%",
    alignSelf: "center",
    marginTop: 10,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  acr__img: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
  },
  blurContainer: {
    height: "100%",
    width: "100%",
  },
  acr_main_view: {
    height: "100%",
    width: "100%",
    paddingLeft: 20,
    paddingTop: 20,
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    position: "relative",
  },
  acr_title: {
    fontSize: 24,
    fontWeight: "500",
    color: "white",
    // letterSpacing: 0.7,
    fontFamily: "Poppins-Medium",
  },
  acr_des: {
    fontSize: 16,
    // letterSpacing: 0.7,
    color: "white",
    marginTop: 4,
    fontFamily: "Poppins-Regular",
  },
  acr_btn: {
    height: 40,
    width: 110,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 20,
    marginTop: 40,
  },
  acr_btn_: {
    height: 40,
    width: 110,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 20,
    // marginTop: 40,
  },
  acr_btn_text: {
    color: "#1D3C89",
    fontSize: 16,
    fontWeight: "500",
  },
  empty: {
    height: 200,
    width: "100%",
  },
  absolute_view_for_svg: {
    position: "absolute",
    right: 10,
    top: 20,
  },
  raft_section: {
    // position: "absolute",
    // bottom: 25,
    // right: 20,
    paddingRight: 10,
  },
  raft_t_1: {
    fontSize: 15,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  raft_t_2: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  raft_t_3: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  raft_s_1: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
    // backgroundColor: "red",
  },
  btn_and_text: {
    height: 60,
    width: "100%",
    // backgroundColor: "red",
    position: "absolute",
    bottom: 20,
    right: 0,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
});
export default styles;
