import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    gap: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "12%",
    // backgroundColor: "green",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "12%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  // starts here
  main_sv: {
    marginTop: 20,
  },
  indi_billing: {
    height: 200,
    width: "86%",
    // backgroundColor: "red",
    borderRadius: 20,
    alignSelf: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    marginBottom: 20,
  },
  top_section: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  booked_text: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.8)",
    letterSpacing: 0.7,
  },
  th_name_section: {
    marginTop: 15,
    marginBottom: 10,
  },
  th_name: {
    fontSize: 20,
    color: "white",
    letterSpacing: 0.7,
    fontWeight: "500",
  },
  th_th_name_section: {
    marginTop: 5,
  },
  th_th_name: {
    fontSize: 16,
    letterSpacing: 0.7,
    color: "rgba(255, 255, 255, 0.7)",
  },
  th_line: {
    height: 1,
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 100,
    marginTop: 15,
  },
  tmp_section: {
    height: 30,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    // backgroundColor: "red",
    marginTop: 10,
    alignItems: "center",
  },
  tmp_text: {
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0.7,
    color: "rgba(255, 255, 255, 0.9)",
  },
  tmp_price_text: {
    fontSize: 20,
    color: "white",
    fontWeight: "500",
  },
  nobill: {
    textAlign: "center",
    color: "white",
    fontSize: 16,
    fontFamily: "Poppins-Regular",
  },
  noHistoryContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
export default styles;
