import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: screenHeight - 270 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  subs_section: {
    height: 430,
    width: 300,
    borderRadius: 20,
    overflow: "hidden",
    zIndex: 10,
  },
  subs_inner: {
    height: "100%",
    width: "100%",
    borderWidth: 1,
    borderRadius: 20,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    alignItems: "center",
    position: "relative",
    padding: 10,
  },
  cue_text: {
    fontSize: 24,
    color: "white",
    fontFamily: "Poppins-Regular",
    marginTop: 30,
    letterSpacing: 0.7,
    lineHeight: 36,
    width: "100%",
    textAlign: "center",
  },
  cle_section: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    marginTop: 50,
    gap: 15,
  },
  cle_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    textAlign: "center",
  },
  tag_line: {
    fontSize: 16,
    color: "white",
    width: "90%",
    textAlign: "center",
    marginTop: 50,
  },
  main_pc_section: {
    marginTop: 30,
    // width: "fit-content",
    height: 45,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    flexDirection: "row",
    position: "relative",
    justifyContent: "flex-end",
    paddingRight: 20,
    position: "absolute",
    bottom: 10,
    paddingLeft: 50,
  },
  mpc_first: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  mpc_circle: {
    height: 35,
    width: 35,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    position: "absolute",
    alignSelf: "center",
    left: 5,
  },
  mpc_second: {
    height: "100%",
    // width: "fit-content",
    display: "flex",
    justifyContent: "center",
  },
  mpc_second_text: {
    color: "white",
    // width: "fit-content",
    fontFamily: "Poppins-Regular",
    // position: "absolute",
    // left: 10,
  },
});
export default styles;
