import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -10,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: -1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
  },
  top_Section: {
    height: 20,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "23%",
  },
  bs_2: {
    height: "100%",
    width: "40%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "23%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  search_section_whole: {
    height: 50,
    width: "100%",
    // backgroundColor: "red",
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    // marginBottom: 10,
  },
  search_section: {
    width: "70%",
    height: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 50,
  },
  filter_section: {
    height: 50,
    width: 50,
    borderRadius: 20,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  finter_section_in: {
    height: "97%",
    width: "96%",
    borderRadius: 20,
    backgroundColor: "rgba(51, 80, 148, 1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  search_section_input: {
    height: "100%",
    width: "100%",
    // backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
  },
  search_svg_section: {
    height: "100%",
    width: "20%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  serach_input_section: {
    height: "100%",
    width: "80%",
  },
  sis_input: {
    height: "100%",
    width: "100%",
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
  top_portion1: {
    height: sb.currentHeight + 10,
    width: "100%",
    // backgroundColor: "red",
  },
  //   starts here
  indi_Journal: {
    height: "100%",
    width: "100%",
    // backgroundColor: "red",
    borderRadius: 20,
    // padding: 10,
    // position: "relative",
    overflow: "hidden",
  },
  main_sv: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 20,
    zIndex: 100,
    marginTop: 30,
  },
  indi_journal_title: {
    fontSize: 18,
    fontWeight: "500",
    color: "white",
    letterSpacing: 0.7,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
  },
  indi_journal_des: {
    fontSize: 14,
    paddingTop: 5,
    fontWeight: "400",
    color: "rgba(255, 255, 255, 0.6)",
    paddingLeft: 10,
    paddingRight: 10,
    height: 80,
    // letterSpacing: 0.7,
  },
  ij_dark: {
    height: "70%",
    width: "100%",
    position: "absolute",
    bottom: 0,
    right: 0,
    display: "flex",
    justifyContent: "flex-end",
    // zIndex: 10,
  },
  j_options: {
    display: "flex",
    flexDirection: "row",
  },
  j_option_indi: {
    height: 30,
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginLeft: 5,
  },
  j_options_indi_text: {
    color: "white",
    fontSize: 12,
  },
  indi_option_date_section: {
    marginBottom: 10,
    paddingLeft: 10,
    paddingTop: 5,
  },
  indi_option_date_text: {
    color: "rgba(255, 255, 255, 0.6)",
    fontSize: 12,
  },
  empty_section: {
    height: 200,
    width: "100%",
  },
  indi_touopa: {
    height: 200,
    width: "40%",
    zIndex: 100,
    // backgroundColor: "red",
    // position: "relative",
  },
  add_section: {
    height: 50,
    width: 50,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  add_section_to: {
    position: "absolute",
    bottom: 90,
    right: 25,
    zIndex: 1000,
  },
  main_scroll_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  subs_section: {
    height: 200,
    width: 300,
    borderRadius: 20,
    overflow: "hidden",
    zIndex: 10,
  },
  subs_inner: {
    height: "100%",
    width: "100%",
    borderWidth: 1,
    borderRadius: 20,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 30,
  },
  cue_text: {
    fontSize: 24,
    color: "white",
    fontFamily: "Poppins-Regular",
    marginTop: 30,
    letterSpacing: 0.7,
    lineHeight: 36,
    width: "100%",
    textAlign: "center",
  },
  cle_section: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    marginTop: 50,
  },
  cle_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  tag_line: {
    fontSize: 16,
    color: "white",
    width: "90%",
    textAlign: "center",
    // marginTop: 50,
    fontFamily: "Poppins-Regular",
  },
  main_pc_section: {
    // marginTop: 30,
    width: "45%",
    height: 45,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    flexDirection: "row",
    position: "relative",
    justifyContent: "flex-end",
    // paddingRight: 20,
  },
  mpc_first: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  mpc_circle: {
    height: 35,
    width: 35,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    position: "absolute",
    alignSelf: "center",
    left: 5,
  },
  mpc_second: {
    height: "100%",
    width: "70%",
    display: "flex",
    justifyContent: "center",
  },
  mpc_second_text: {
    color: "white",
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
