import { StyleSheet, Platform, StatusBar as sb } from "react-native";
("expo-status-bar");
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  top_portion1: {
    height: 20 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 40,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    zIndex: 10,
    gap: 10,
    // backgroundColor: "red",
  },
  bs_1: {
    height: "100%",
    width: "12%",
    // backgroundColor: "green",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "12%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  name_profile_section: {
    height: 100,
    width: "86%",
    // backgroundColor: "red",
    marginTop: 20,
    alignSelf: "center",
    borderRadius: 20,
    display: "flex",
    flexDirection: "row",
    // justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  profile_section: {
    height: "100%",
    width: "30%",
    // borderRadius: 100,
    // backgroundColor: "green",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  name_section: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
  },
  profile_img: {
    height: 80,
    width: 80,
    borderRadius: 100,
    objectFit: "cover",
  },
  name_text: {
    fontSize: 24,
    fontWeight: "500",
    color: "rgba(255,255,255,0.9)",
    paddingLeft: 10,
    letterSpacing: 0.7,
  },
  edit_section: {
    height: 35,
    width: 120,
    backgroundColor: "red",
    borderRadius: 100,
    marginLeft: 10,
    marginTop: 4,
    display: "flex",
    flexDirection: "row",
    overflow: "hidden",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
    paddingLeft: 5,
    paddingRight: 5,
  },
  edit_section_svg_section: {
    height: "100%",
    width: "30%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  edit_section_text_section: {
    height: "100%",
    width: "70%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  es_text: {
    fontSize: 12,
    letterSpacing: 0.7,
    color: "white",
  },
  indi_options: {
    height: 60,
    width: "86%",
    // backgroundColor: "red",
    alignSelf: "center",
    marginTop: 15,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  indi_options_to: {
    height: 60,
    width: "47%",
    // backgroundColor: "red",
    alignSelf: "center",
    // marginTop: 15,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  two_options_in_one: {
    height: 60,
    width: "86%",
    // backgroundColor: "red",
    alignSelf: "center",
    marginTop: 15,
    // borderRadius: 100,
    // borderWidth: 1.5,
    // borderColor: "rgba(255, 255, 255, 0.1)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
    // backgroundColor: "red",
  },
  indi_option_svg_section_LO: {
    height: "100%",
    width: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    // backgroundColor: "red",
  },
  indi_option_svg_section_LO_to: {
    height: "100%",
    width: "30%",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    // backgroundColor: "red",
  },
  io_name_section_lo_to: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    // paddingLeft: 20,
  },
  io_name_section_lo: {
    height: "100%",
    width: "80%",
    display: "flex",
    justifyContent: "center",
    // paddingLeft: 20,
  },
  io_name: {
    color: "white",
    fontSize: 16,
    letterSpacing: 0.7,
  },
});
export default styles;
