import {
  StyleSheet,
  Platform,
  StatusBar as sb,
  Dimensions,
} from "react-native";
("expo-status-bar");
const screenHeight = Dimensions.get("window").height;
const styles = StyleSheet.create({
  sav: {
    height: "100%",
    width: "100%",
    // paddingTop: Platform.OS == "ios" ? 0 : sb.currentHeight,
  },
  backgroundView: {
    height: "130%",
    width: "100%",
    position: "absolute",
    // backgroundColor: "red",
    zIndex: -1,
    top: 0,
    left: 0,
  },
  backgroundImage: {
    height: "130%",
    width: "100%",
    resizeMode: "cover",
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    opacity: 0.25,
  },
  main_scroll_view: {
    height: "100%",
    width: "100%",
    zIndex: 10,
    marginTop: 20,
  },
  main_view: {
    height: screenHeight - 55 - 10,
    width: "100%",
    // zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  top_portion1: {
    height: 10 + sb.currentHeight,
    width: "100%",
    // backgroundColor: "red",
  },
  top_portion: {
    height: 40,
    width: "100%",
    // backgroundColor: "red",
  },
  back_section: {
    height: 55,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    // backgroundColor: "red",
    zIndex: 10,
  },
  bs_1: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2: {
    height: "100%",
    width: "60%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  bs_3: {
    height: "100%",
    width: "20%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle: {
    height: 40,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_stroke_circle: {
    height: "100%",
    width: "100%",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_1_circle_circle: {
    height: "94%",
    width: "94%",
    backgroundColor: "rgba(51, 80, 148, 1)",
    borderRadius: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bs_2_cue: {
    textAlign: "center",
    fontSize: 16,
    color: "white",
    fontWeight: 400,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  input_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
  },
  input_whole_section_btn: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // position: "absolute",
    // bottom: 25,
    zIndex: 10,
    // marginTop: (screenHeight * 28) / 100,
    marginBottom: 20,
  },
  input_inner_section: {
    height: "100%",
    width: "90%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    // overflow: "hidden",
    // justifyContent: "space-between",
    gap: 8,
  },
  input_inner_section_btn: {
    height: "100%",
    width: "85%",
    borderRadius: 100,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  svg_circle: {
    height: 60,
    width: 40,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  svg_circle_eye: {
    height: 60,
    width: 60,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },
  input_section: {
    height: "100%",
    width: 210,
    // backgroundColor: "green",
  },
  input_section_: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    // backgroundColor: "green",
  },
  input_section_text: {
    height: "100%",
    width: 180,
    display: "flex",
    justifyContent: "center",
  },
  input: {
    height: "100%",
    width: "100%",
    letterSpacing: 1,
    fontSize: 14,
    color: "white",
    // fontFamily: "Poppins-Regular",
    // paddingBottom: 0,
    // backgroundColor: "red",
    overflow: "hidden",
    paddingLeft: 20,
  },
  input_text: {
    letterSpacing: 1,
    fontSize: 14,
    color: "#ffffff90",
    // paddingLeft: 6,
    textTransform: "capitalize",
    // paddingLeft: 20,
    // fontFamily: "Poppins-Regular",
  },
  input_text_active: {
    letterSpacing: 1,
    fontSize: 14,
    color: "#ffffff",
    paddingLeft: 6,
    textTransform: "capitalize",
    paddingLeft: 20,
  },
  bs_whole_view: {
    height: "100%",
    alignItems: "center",
    gap: 10,
  },
  option_indi_whole: {
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
  },
  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  oi_dot_section: {
    height: "100%",
    width: 55,
    // backgroundColor: "orange",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  oi_dot: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "50%",
  },
  oi_dot_active: {
    height: 20,
    width: 20,
    backgroundColor: "rgba(0, 157, 255, 1)",
    borderRadius: "50%",
    borderColor: "rgba(255, 255, 255, 0.5)",
    borderWidth: 2,
  },
  oi_text_section: {
    height: "100%",
    display: "flex",
    justifyContent: "center",
  },
  oi_text: {
    fontSize: 18,
    fontWeight: "400",
    color: "white",
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
  },
  yourstory_input_section: {
    // height: 400,
    width: "90%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderRadius: 20,
    zIndex: 10,
    padding: 8,
    // marginTop: 20,
    alignSelf: "center",
    paddingBottom: 10,
    marginBottom: 10,
  },
  ts_text: {
    fontSize: 20,
    fontFamily: "Poppins-Medium",
    color: "white",
    textAlign: "center",
    marginTop: 10,
  },
  pg_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    marginTop: 10,
    color: "#ffffff90",
    paddingLeft: 10,
  },
  pg_text_: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    // marginTop: 10,
    color: "#ffffff90",
    paddingLeft: 10,
  },
  dt_whole_section: {
    height: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 10,
    marginTop: 10,
  },
  date_time_section_d: {
    height: 40,
    width: "47%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  date_time_section_d_: {
    height: 40,
    width: "47%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    // borderWidth: 1.5,
    // borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  date_time_section_t: {
    height: 40,
    width: "47%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
    borderRadius: 50,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    position: "relative",
  },
  av_svg: {
    position: "absolute",
    left: 10,
  },
  dt_text_100: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "white",
    textAlign: "flex-start",
    width: "100%",
    // textAlign: "center",
    paddingLeft: 40,
    // backgroundColor: "red",
  },
  country_scroll: {
    width: "100%",
    height: "100%",
  },
  oi_dot_section_empty: {
    height: 0,
    width: 20,
  },
  oi_empty_section: {
    height: "100%",
    width: "10%",
  },
  last_empty_space_rb: {
    height: 30,
    width: "100%",
  },
  input_whole_section_btn_time: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 0,
  },
  login_text: {
    fontSize: 16,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  vi_circle: {
    height: 15,
    width: 15,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.19)",
  },
  vi_circle_active: {
    height: 15,
    width: 15,
    borderRadius: 100,
    backgroundColor: "#009DFF",
  },
  is_indi: {
    height: "100%",
    width: "50%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    // backgroundColor: "red",
  },
  vi_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  price_section_eb: {
    height: 35,
    width: "fit-content",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1.5,
    gap: 10,
  },
  ebts: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 50,
    // backgroundColor: "red",
  },
  eb_input: {
    height: "100%",
    width: "fit-content",
    minWidth: 30,
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  eb_line: {
    height: "90%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    width: 1.5,
  },
  cur_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    textAlign: "center",
  },
  discount_section: {
    height: 35,
    width: 80,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 100,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  dis_text: {
    fontSize: 14,
    color: "white",
  },
  ft_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  discription_input: {
    width: "100%",
    height: 300,
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    padding: 10,
  },
  cc_view_: {
    width: "100%",
    paddingLeft: 12,
    paddingRight: 10,
    // marginTop: 30,
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  cc_text: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  login_text: {
    fontSize: 18,
    color: "#0F1C4E",
    fontFamily: "Poppins-Regular",
  },
  multiple_text: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "white",
  },
  clt_label: {
    paddingLeft: 40,
    marginTop: 20,
    marginBottom: 10,
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
  },
  bs_whole_view_cat: {
    // height: "100%",
    width: "100%",
    gap: 10,
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    paddingLeft: 10,
    paddingRight: 10,
    // backgroundColor: "red",
  },
  empty_category_view: {
    height: 140,
    width: "100%",
  },

  option_indi: {
    height: 60,
    width: "85%",
    // backgroundColor: "red",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 50,
    borderWidth: 1.2,
    borderColor: "#ffffff17",
  },
  indi_tag: {
    height: 45,
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    zIndex: 100,
  },
  indi_tag_active: {
    height: 45,
    paddingLeft: 20,
    paddingRight: 20,
    display: "flex",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    zIndex: 100,
    backgroundColor: "white",
  },
  indi_tag_text: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  indi_tag_text_active: {
    fontSize: 14,
    color: "rgba(30, 63, 142, 1)",
    fontFamily: "Poppins-Regular",
    letterSpacing: 0.7,
  },
  input_whole_section: {
    height: 60,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
  },
  // input_inner_section: {
  //   height: "fit-content",
  //   width: "85%",
  //   borderRadius: 100,
  //   borderWidth: 1.2,
  //   borderColor: "#ffffff17",
  //   flexDirection: "row",
  //   // overflow: "hidden",
  //   // justifyContent: "space-between",
  //   gap: 8,
  // },
  input_section_text_nsvg: {
    height: "fit-content",
    width: 220,
    display: "flex",
    justifyContent: "center",
    paddingLeft: 20,
  },
  svg_circle_eye: {
    height: 60,
    width: 60,
    borderRadius: "50%",
    // backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
  },
  clt_label: {
    paddingLeft: 40,
    marginTop: 20,
    marginBottom: 10,
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#ffffff90",
  },
  input_text_active_level: {
    letterSpacing: 1,
    fontSize: 12,
    color: "#ffffff",
    paddingLeft: 6,
    textTransform: "capitalize",
    fontFamily: "Poppins-Regular",
  },

  // preview starts here
  main_event: {
    width: "86%",
    // height: "fit-content",
    maxHeight: screenHeight - 200,
    // backgroundColor: "red",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
    paddingBottom: 2,
    // paddingTop: 2,
  },
  indi_event_img_section: {
    height: 160,
    width: "94%",
    backgroundColor: "red",
    alignSelf: "center",
    marginTop: 8,
    marginBottom: 10,
    borderRadius: 15,
    overflow: "hidden",
  },
  ie_img: {
    height: "100%",
    width: "100%",
    objectFit: "cover",
  },
  indi_events_bottom: {
    height: "fit-content",
    width: "97%",
    alignSelf: "center",
    display: "flex",
    flexDirection: "row",
  },
  ie_left: {
    height: "100%",
    width: "65%",
    display: "flex",
    // backgroundColor: "red",
  },
  ie_right: {
    height: "fit-content",
    width: "35%",
    // backgroundColor: "green",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  ie_left_event_name_view: {
    height: "fit-content",
    width: "fit-content",
  },
  event_name: {
    fontSize: 18,
    color: "white",
    fontWeight: "400",
    paddingLeft: 10,
    marginTop: 10,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    // backgroundColor: "green",
  },
  event_host: {
    fontSize: 14,
    color: "#ffffff90",
    paddingLeft: 10,
    marginTop: 2,
    letterSpacing: 0.7,
    fontFamily: "Poppins-Regular",
    // backgroundColor: "green",
  },
  ie_time_section: {
    display: "flex",
    flexDirection: "row",
    paddingLeft: 10,
    marginTop: 10,
    gap: 8,
    alignItems: "center",
    // backgroundColor: "red",
  },
  event_time: {
    fontSize: 14,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  event_date_section: {
    height: 80,
    width: 70,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  event_date: {
    fontSize: 16,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  about_the_workshop_section: {
    width: "97%",
    height: "fit-content",
    // marginBottom: 20,
    marginTop: 30,
  },
  atw_title: {
    fontSize: 18,
    letterSpacing: 0.7,
    paddingLeft: 10,
    color: "white",
    fontFamily: "Poppins-Regular",
  },
  atw_des: {
    fontSize: 14,
    letterSpacing: 0.7,
    paddingLeft: 10,
    color: "rgba(255, 255, 255, 0.7)",
    marginTop: 6,
    fontFamily: "Poppins-Regular",
    fontWeight: "300",
    // verticalAlign: "center",
  },
  li: {
    fontSize: 14,
    letterSpacing: 0.7,
    paddingLeft: 5,
    color: "rgba(255, 255, 255, 0.7)",
    fontWeight: "300",
    fontFamily: "Poppins-Regular",
    // marginTop: 6,
    // verticalAlign: "center",
  },
  dot: {
    height: 5,
    width: 5,
    borderRadius: 100,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    // marginRight: 6,
  },
  ul: {
    width: "100%",
    paddingLeft: 10,
    marginTop: 5,
    display: "flex",
    flexDirection: "row",
  },
  ul_text_section: {
    display: "flex",
    // alignItems: "center",
    // backgroundColor: "red",
  },
  dot_section: {
    width: 10,
    height: "fit-content",
    // backgroundColor: "green",
    display: "flex",
    // justifyContent: "center",
    alignItems: "center",
    paddingTop: 7,
  },
  book_now_btn_section: {
    width: "86%",
    height: 60,
    backgroundColor: "white",
    alignSelf: "center",
    marginTop: 20,
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bn_text: {
    fontSize: 18,
    fontWeight: "600",
    color: "rgba(15, 28, 78, 1)",
    textAlign: "center",
  },
});
export default styles;
